version: '3.8'
services:
  app:
    image: your-dockerhub-id/your-repo:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      TZ: Asia/Seoul
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: postgres:15-alpine
    container_name: prod-postgres
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: scripter_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - prod-db-data:/var/lib/postgresql/data

volumes:
  prod-db-data: