version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: ozazak-jenkins   # <--- [중요] 이 이름으로 Nginx가 찾습니다
    user: root
    privileged: true
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/S14P11B205:/home/ubuntu/S14P11B205
    environment:
      - TZ=Asia/Seoul
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - ozazak-network
    restart: always

volumes:
  jenkins-data:

networks:
  ozazak-network:
    external: true