version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ozazak-postgres-local
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data-local:/var/lib/postgresql/data
    networks:
      - ozazak-network

  redis:
    image: redis:7-alpine
    container_name: ozazak-redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis-data-local:/data
    networks:
      - ozazak-network

#  back:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: ozazak-back-local
#    depends_on:
#      - postgres
#      - redis
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
#      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#      SPRING_PROFILES_ACTIVE: local
#    ports:
#      - "8080:8080"
#    networks:
#      - ozazak-network

volumes:
  postgres-data-local:
  redis-data-local:

networks:
  ozazak-network:
    driver: bridge