-- Generated by match_recruitment_category.py
-- Date: 2026-02-05 12:59:50

-- SKIPPED (low similarity 0.4953): '카드사업팀' -> '고객응대·CS'
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 457;
-- Matched: 'IT보안/기획팀' -> '서비스기획·PM' (0.5957)
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 458;
-- Matched: '태그리스 솔루션팀' -> 'IT·솔루션·기술영업' (0.5604)
-- SKIPPED (low similarity 0.4823): '정산운영팀 (보훈대상자 전용)' -> '안전관리'
UPDATE recruitment SET category_id = 190 WHERE recruitment_id = 460;
-- Matched: '디자인' -> '광고 디자인' (0.6388)
-- SKIPPED (low similarity 0.3891): '메디큐브 미국 틱톡샵 어필리에이트 마케팅' -> '마케팅전략·기획'
UPDATE recruitment SET category_id = 29 WHERE recruitment_id = 462;
-- Matched: '비서' -> '비서' (1.0000)
-- SKIPPED (low similarity 0.3777): '빌링' -> '채용'
-- SKIPPED (low similarity 0.4689): '스탭' -> '무대·스탭·오퍼레이터'
-- SKIPPED (low similarity 0.4652): '[GC그룹 어니스트리] 멀티채널 영업' -> '영업관리·지원·기획'
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 466;
-- Matched: '디지털 마케팅 기획' -> '마케팅전략·기획' (0.7079)
UPDATE recruitment SET category_id = 38 WHERE recruitment_id = 467;
-- Matched: '디지털 마케팅 운영' -> '퍼포먼스·온라인마케팅' (0.6318)
UPDATE recruitment SET category_id = 12 WHERE recruitment_id = 468;
-- Matched: '채용운영 (계약직)' -> '채용' (0.6563)
UPDATE recruitment SET category_id = 233 WHERE recruitment_id = 469;
-- Matched: '교육운영 (계약직)' -> '교육개발·기획' (0.6056)
-- SKIPPED (low similarity 0.3121): '순환기내과(심장뇌혈관시술센터)' -> '안전관리'
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 471;
-- Matched: '연구기획관리팀-행정-연구지원' -> '영업관리·지원·기획' (0.5828)
-- SKIPPED (low similarity 0.4001): '범어동지점' -> '해외영업'
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 473;
-- Matched: '영업 및 마케팅-SW 기술마케팅' -> '마케팅전략·기획' (0.6348)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 474;
-- Matched: '해외분야-해외영업' -> '해외영업' (0.8789)
-- SKIPPED (low similarity 0.3995): '안과검사실' -> '안전관리'
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 476;
-- Matched: '메디컬 플랫폼 B2B세일즈' -> 'B2B영업·법인영업' (0.5704)
-- SKIPPED (low similarity 0.4755): '정규직 6급' -> '초·중·고 교사'
-- SKIPPED (low similarity 0.4870): '사원' -> '은행원'
UPDATE recruitment SET category_id = 50 WHERE recruitment_id = 479;
-- Matched: '글로벌물류운영' -> '물류관리·기획' (0.7093)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 480;
-- Matched: '사업관리(C-1)' -> '영업관리·지원·기획' (0.6250)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 481;
-- Matched: '사업관리(C-2)' -> '영업관리·지원·기획' (0.6331)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 482;
-- Matched: '사업관리(C-3)' -> '영업관리·지원·기획' (0.6404)
-- SKIPPED (low similarity 0.3502): '심장혈관•부정맥센터-간호사' -> '안전관리'
UPDATE recruitment SET category_id = 38 WHERE recruitment_id = 484;
-- Matched: '퍼포먼스마케터' -> '퍼포먼스·온라인마케팅' (0.7142)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 485;
-- Matched: '전문연구요원(병역특례)_반도체/디스플레이 공정소재 개발, 이차전지, 계산화학, 기능성 코팅소재' -> '반도체·디스플레이' (0.5403)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 486;
-- Matched: '디스플레이 공정 소개 개발_디스플레이용 감광성 수지 개발 및 연구' -> '반도체·디스플레이' (0.5137)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 487;
-- Matched: '디스플레이 공정 소개 개발_OLED 유기 재료 합성 및 재료 분석' -> '반도체·디스플레이' (0.5301)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 488;
-- Matched: '반도체 공정 소재 개발_Photoresist 또는 BARC, SOC 소재 합성' -> '반도체·디스플레이' (0.5500)
-- SKIPPED (low similarity 0.4992): '반도체 공정 소재 개발_HBM&PKG 공정용 신규 Wet Chemical 합성' -> '반도체·디스플레이'
-- SKIPPED (low similarity 0.3949): '이차전지 공정 소재 개발_도전재 소재 및 슬러리 개발' -> '반도체·디스플레이'
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 491;
-- Matched: '반도체 공정 소재 양산화(Scale-up)' -> '반도체·디스플레이' (0.5369)
-- SKIPPED (low similarity 0.3893): '원자재 검증 및 기술 분석' -> '자재'
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 493;
-- Matched: '제품 품질관리 및 고객 대응' -> '품질관리' (0.7396)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 494;
-- Matched: '반도체 재료 기술영업 및 해외 마케팅' -> '반도체·디스플레이' (0.6535)
UPDATE recruitment SET category_id = 225 WHERE recruitment_id = 495;
-- Matched: '일반회계 및 세무' -> '회계·세무·CPA·CFA' (0.7321)
UPDATE recruitment SET category_id = 80 WHERE recruitment_id = 496;
-- Matched: '[Yanolja NEXT] Software Engineer' -> '데이터엔지니어' (0.5232)
-- SKIPPED (low similarity 0.4861): '[Yanolja NEXT] Software Engineer - IAB (Service & Product)' -> '데이터엔지니어'
UPDATE recruitment SET category_id = 6 WHERE recruitment_id = 498;
-- Matched: '글로벌투자분석실' -> '경영분석·컨설턴트' (0.5153)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 499;
-- Matched: '리스크관리실' -> '안전관리' (0.5960)
-- SKIPPED (low similarity 0.4040): 'Lead Software Engineer - IAB' -> '시스템프로그래머'
-- SKIPPED (low similarity 0.4954): '[Yanolja NEXT] Software Engineer - Price Intelligence' -> '데이터엔지니어'
UPDATE recruitment SET category_id = 66 WHERE recruitment_id = 502;
-- Matched: 'Product Manager' -> '상품기획·MD' (0.5113)
UPDATE recruitment SET category_id = 80 WHERE recruitment_id = 503;
-- Matched: '[Yanolja NEXT] Data Engineer' -> '데이터엔지니어' (0.6120)
UPDATE recruitment SET category_id = 162 WHERE recruitment_id = 504;
-- Matched: '기계(1)' -> '기계' (0.8247)
UPDATE recruitment SET category_id = 162 WHERE recruitment_id = 505;
-- Matched: '기계(2)' -> '기계' (0.8434)
UPDATE recruitment SET category_id = 177 WHERE recruitment_id = 506;
-- Matched: '전기(1)' -> '전기·전자·제어' (0.5958)
UPDATE recruitment SET category_id = 135 WHERE recruitment_id = 507;
-- Matched: '전기(2)' -> '전기·통신' (0.6039)
UPDATE recruitment SET category_id = 177 WHERE recruitment_id = 508;
-- Matched: '전기(3)' -> '전기·전자·제어' (0.6122)
UPDATE recruitment SET category_id = 135 WHERE recruitment_id = 509;
-- Matched: '정보통신 / IT (1)' -> '전기·통신' (0.5826)
UPDATE recruitment SET category_id = 135 WHERE recruitment_id = 510;
-- Matched: '정보통신 / IT (2)' -> '전기·통신' (0.5969)
UPDATE recruitment SET category_id = 135 WHERE recruitment_id = 511;
-- Matched: '정보통신 / IT (3)' -> '전기·통신' (0.5785)
UPDATE recruitment SET category_id = 135 WHERE recruitment_id = 512;
-- Matched: '정보통신 / IT (4)' -> '전기·통신' (0.5745)
UPDATE recruitment SET category_id = 135 WHERE recruitment_id = 513;
-- Matched: '정보통신 / IT (5)' -> '전기·통신' (0.5696)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 514;
-- Matched: '행정(1)' -> '현장·시공·감리·공무' (0.5710)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 515;
-- Matched: '행정(2)' -> '현장·시공·감리·공무' (0.5773)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 516;
-- Matched: '행정(3)' -> '현장·시공·감리·공무' (0.6125)
-- SKIPPED (low similarity 0.3877): '자기부상철도궤도' -> '총무'
-- SKIPPED (low similarity 0.4578): '공항통신 영상 PD' -> '전기·통신'
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 519;
-- Matched: '경영기획' -> '경영기획' (1.0000)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 520;
-- Matched: '가맹점 관리' -> '영업관리·지원·기획' (0.5563)
UPDATE recruitment SET category_id = 135 WHERE recruitment_id = 521;
-- Matched: '전기/계장' -> '전기·통신' (0.5940)
-- SKIPPED (low similarity 0.4878): '조직문화' -> '공정관리'
UPDATE recruitment SET category_id = 59 WHERE recruitment_id = 523;
-- Matched: '구매' -> '구매' (1.0000)
UPDATE recruitment SET category_id = 168 WHERE recruitment_id = 524;
-- Matched: '화장품 원료평가/제형개발' -> '화장품' (0.5812)
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 525;
-- Matched: '기술영업' -> 'IT·솔루션·기술영업' (0.6641)
UPDATE recruitment SET category_id = 219 WHERE recruitment_id = 526;
-- Matched: '분석연구' -> '리서치·시장조사' (0.5972)
UPDATE recruitment SET category_id = 106 WHERE recruitment_id = 527;
-- Matched: '환경관리' -> '환경관리' (1.0000)
UPDATE recruitment SET category_id = 56 WHERE recruitment_id = 528;
-- Matched: '무역사무' -> '무역·수출입관리' (0.7257)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 529;
-- Matched: '품질검사' -> '품질관리' (0.7517)
UPDATE recruitment SET category_id = 50 WHERE recruitment_id = 530;
-- Matched: '[SCM] 국내물류 B2C 출고운영 채용연계형 인턴사원 모집' -> '물류관리·기획' (0.5553)
UPDATE recruitment SET category_id = 69 WHERE recruitment_id = 531;
-- Matched: 'QC' -> 'QA' (0.7337)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 533;
-- Matched: '영업직(MR)_서울' -> 'B2B영업·법인영업' (0.5921)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 534;
-- Matched: '영업직(MR)_경기' -> 'B2B영업·법인영업' (0.5762)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 535;
-- Matched: '영업직(MR)_충북' -> 'B2B영업·법인영업' (0.5312)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 536;
-- Matched: '영업직(MR)_충남' -> 'B2B영업·법인영업' (0.5407)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 537;
-- Matched: '영업직(MR)_광주전남' -> '영업관리·지원·기획' (0.5248)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 538;
-- Matched: '영업직(MR)_대구경북' -> 'B2B영업·법인영업' (0.5466)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 539;
-- Matched: '영업직(MR)_부산' -> 'B2B영업·법인영업' (0.5592)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 540;
-- Matched: '해외영업' -> '해외영업' (1.0000)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 541;
-- Matched: '생산관리' -> '생산관리' (1.0000)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 542;
-- Matched: '안전환경' -> '안전관리' (0.7281)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 543;
-- Matched: '공무(기계설비)' -> '일반사무' (0.6007)
UPDATE recruitment SET category_id = 177 WHERE recruitment_id = 544;
-- Matched: '계전(전기설비)' -> '전기·전자·제어' (0.5260)
-- SKIPPED (low similarity 0.4718): '[KP그룹]KP한석화학 LAB BIZ팀 백앤드 개발자' -> '서비스기획·PM'
-- SKIPPED (low similarity 0.3924): '[KP그룹]한국석유공업 기술연구소 연구원 채용(경력)' -> '경영분석·컨설턴트'
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 547;
-- Matched: '[KP그룹]한국석유공업 경영기획실 기획팀 채용(경력)' -> '경영기획' (0.5599)
-- SKIPPED (low similarity 0.4607): 'Merchandising Associate' -> '상품기획·MD'
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 549;
-- Matched: '화장품 제조 및 품질관리 양성과정' -> '품질관리' (0.5952)
-- SKIPPED (low similarity 0.3534): '간호사-순환기내과(심장예방재활센터)' -> '안전관리'
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 551;
-- Matched: '연구직_안전해석' -> '안전관리' (0.5713)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 552;
-- Matched: '연구직_중대사고/확률론적 안전성평가' -> '안전관리' (0.5246)
UPDATE recruitment SET category_id = 137 WHERE recruitment_id = 553;
-- Matched: '연구직_기계' -> '기계·설비·화학' (0.5383)
-- SKIPPED (low similarity 0.4878): '연구직_재료' -> '리서치·시장조사'
-- SKIPPED (low similarity 0.4188): '연구직_계통열수력' -> '물류관리·기획'
-- SKIPPED (low similarity 0.4265): '연구직_원자력-비경수형' -> '경영기획'
UPDATE recruitment SET category_id = 177 WHERE recruitment_id = 557;
-- Matched: '연구직_계측제어' -> '전기·전자·제어' (0.6011)
-- SKIPPED (low similarity 0.4628): '연구직_전력계통' -> '경영기획'
-- SKIPPED (low similarity 0.4938): '연구직_구조' -> '리서치·시장조사'
-- SKIPPED (low similarity 0.4678): '연구직_부지' -> '현장·시공·감리·공무'
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 561;
-- Matched: '연구직_품질보증' -> '품질관리' (0.5956)
-- SKIPPED (low similarity 0.4444): '연구직_방사능방재' -> '안전관리'
-- SKIPPED (low similarity 0.4514): '연구직_방사선방호' -> '보안·경비·경호'
-- SKIPPED (low similarity 0.4386): '연구직_방사성폐기물' -> '환경관리'
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 565;
-- Matched: '연구직_계통성능 및 SW기술' -> '서비스기획·PM' (0.5031)
UPDATE recruitment SET category_id = 177 WHERE recruitment_id = 566;
-- Matched: '연구직_기기건전성 및 SW기술' -> '전기·전자·제어' (0.5267)
-- SKIPPED (low similarity 0.4661): '연구직_정보기술' -> '리서치·시장조사'
UPDATE recruitment SET category_id = 101 WHERE recruitment_id = 568;
-- Matched: '행정직_경영관리' -> '공정관리' (0.6543)
UPDATE recruitment SET category_id = 137 WHERE recruitment_id = 569;
-- Matched: '행정직_기계(설비)' -> '기계·설비·화학' (0.6168)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 570;
-- Matched: '행정직_경영관리(보훈제한)' -> '경영기획' (0.6106)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 571;
-- Matched: '서비스 매니저(서산)' -> '서비스기획·PM' (0.6212)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 572;
-- Matched: '서비스 매니저(송도)' -> '서비스기획·PM' (0.6509)
-- SKIPPED (low similarity 0.4442): '전시' -> '구매'
-- SKIPPED (low similarity 0.4565): '유물자료관리' -> '안전관리'
-- SKIPPED (low similarity 0.4460): '유물자료관리(장애인 제한)' -> '안전관리'
UPDATE recruitment SET category_id = 219 WHERE recruitment_id = 576;
-- Matched: '학술연구' -> '리서치·시장조사' (0.5328)
-- SKIPPED (low similarity 0.4758): '조경' -> '토목·조경·도시'
UPDATE recruitment SET category_id = 59 WHERE recruitment_id = 578;
-- Matched: '행사' -> '구매' (0.5345)
-- SKIPPED (low similarity 0.4267): '경기도 양자인공지능지원센터장' -> '빅데이터·AI'
UPDATE recruitment SET category_id = 11 WHERE recruitment_id = 580;
-- Matched: '교육운영' -> '교육' (0.7371)
UPDATE recruitment SET category_id = 101 WHERE recruitment_id = 581;
-- Matched: '공정서비스 (육아휴직대체)' -> '공정관리' (0.5757)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 607;
-- Matched: '[일반전형]수원지사 - 기술' -> '일반사무' (0.5693)
UPDATE recruitment SET category_id = 18 WHERE recruitment_id = 582;
-- Matched: '세무회계 (육아기근로시간 단축대체)' -> '세무' (0.5764)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 583;
-- Matched: '[일반전형]본사 - 행정' -> '일반사무' (0.6184)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 584;
-- Matched: '[일반전형]본사 - 기술' -> '일반사무' (0.5531)
-- SKIPPED (low similarity 0.4508): '[일반전형]도로교통연구원 - 기술' -> '토목·조경·도시'
UPDATE recruitment SET category_id = 233 WHERE recruitment_id = 586;
-- Matched: '[일반전형]인재개발원 - 행정' -> '교육개발·기획' (0.5701)
-- SKIPPED (low similarity 0.4910): '[일반전형]교통관제센터 - 기술' -> '안전관리'
-- SKIPPED (low similarity 0.4809): '[일반전형]첨단기계화센터 - 기술' -> '기계·설비·화학'
-- SKIPPED (low similarity 0.4730): '[일반전형]김포파주건설사업단 - 기술' -> '일반사무'
UPDATE recruitment SET category_id = 139 WHERE recruitment_id = 590;
-- Matched: '[일반전형]수도권건설사업단 - 기술' -> '토목·조경·도시' (0.5079)
UPDATE recruitment SET category_id = 111 WHERE recruitment_id = 591;
-- Matched: '[일반전형]세종천안건설사업단 - 행정' -> '설치·정비·AS·시공·공무' (0.5249)
-- SKIPPED (low similarity 0.4802): '[일반전형]세정천안건설사업단 - 기술' -> '설치·정비·AS·시공·공무'
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 593;
-- Matched: '[일반전형]서산아산건설사업단 - 행정' -> '일반사무' (0.5360)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 594;
-- Matched: '[일반전형]강진광주건설사업단 - 행정' -> '일반사무' (0.5105)
-- SKIPPED (low similarity 0.4769): '[일반전형]경남권건설사업단 - 기술' -> '일반사무'
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 596;
-- Matched: '[일반전형]남부도로개량사업단 - 행정' -> '일반사무' (0.5370)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 597;
-- Matched: '[일반전형]수도권본부 - 행정' -> '일반사무' (0.5611)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 598;
-- Matched: '[일반전형]수도권본부 - 기술' -> '일반사무' (0.5581)
-- SKIPPED (low similarity 0.4682): '[일반전형]인천지사 - 기술' -> '일반사무'
-- SKIPPED (low similarity 0.4801): '[일반전형]시흥지사 - 기술' -> '일반사무'
-- SKIPPED (low similarity 0.4989): '[일반전형]군포지사 - 행정' -> '일반사무'
-- SKIPPED (low similarity 0.4711): '[일반전형]군포지사 - 기술' -> '일반사무'
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 603;
-- Matched: '[일반전형]파주지사 - 행정' -> '현장·시공·감리·공무' (0.5418)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 604;
-- Matched: '[일반전형]서울경기본부 - 행정' -> '일반사무' (0.5456)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 605;
-- Matched: '[일반전형]서울경기본부 - 기술' -> '일반사무' (0.5050)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 606;
-- Matched: '[일반전형]수원지사 - 행정' -> '일반사무' (0.5928)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 608;
-- Matched: '[일반전형]경기광주지사 - 행정' -> '일반사무' (0.5457)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 609;
-- Matched: '[일반전형]강원본부 - 행정' -> '일반사무' (0.5394)
-- SKIPPED (low similarity 0.4961): '[일반전형]강원본부 - 기술' -> '일반사무'
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 611;
-- Matched: '[일반전형]원주지사 - 행정' -> '현장·시공·감리·공무' (0.5367)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 612;
-- Matched: '[일반전형]대관령지사 - 행정' -> '현장·시공·감리·공무' (0.5379)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 613;
-- Matched: '[일반전형]홍천지사 - 행정' -> '현장·시공·감리·공무' (0.5439)
-- SKIPPED (low similarity 0.4960): '[일반전형]충북본부 - 행정' -> '일반사무'
-- SKIPPED (low similarity 0.4961): '[일반전형]충북본부 - 기술' -> '일반사무'
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 616;
-- Matched: '[일반전형]진천지사 - 행정' -> '현장·시공·감리·공무' (0.5667)
-- SKIPPED (low similarity 0.4445): '[일반전형]진천지사 - 기술' -> '현장·시공·감리·공무'
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 618;
-- Matched: '[일반전형]제천지사 - 행정' -> '현장·시공·감리·공무' (0.5348)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 619;
-- Matched: '[일반전형]충주지사 - 행정' -> '현장·시공·감리·공무' (0.5593)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 620;
-- Matched: '[일반전형]엄정지사 - 행정' -> '현장·시공·감리·공무' (0.5302)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 621;
-- Matched: '[일반전형]대전충남본부 - 행정' -> '일반사무' (0.5558)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 622;
-- Matched: '[일반전형]대전충남본부 - 기술' -> '일반사무' (0.5326)
-- SKIPPED (low similarity 0.4508): '[일반전형]천안지사 - 기술' -> '일반사무'
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 624;
-- Matched: '[일반전형]대전지사 - 행정' -> '일반사무' (0.5464)
-- SKIPPED (low similarity 0.4915): '[일반전형]영동지사 - 기술' -> '현장·시공·감리·공무'
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 626;
-- Matched: '[일반전형]당진지사 - 행정' -> '현장·시공·감리·공무' (0.5210)
-- SKIPPED (low similarity 0.4059): '[일반전형]공주지사 - 기술' -> '현장·시공·감리·공무'
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 628;
-- Matched: '[일반전형]부여지사 - 행정' -> '현장·시공·감리·공무' (0.5337)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 629;
-- Matched: '[일반전형]전북본부 - 행정' -> '일반사무' (0.5587)
-- SKIPPED (low similarity 0.4771): '[일반전형]전북본주 - 기술' -> '일반사무'
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 631;
-- Matched: '[일반전형]전주지사 - 행정' -> '현장·시공·감리·공무' (0.5451)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 632;
-- Matched: '[일반전형]논산지사 - 행정' -> '일반사무' (0.5071)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 633;
-- Matched: '[일반전형]광주전남본부 - 행정' -> '일반사무' (0.5549)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 634;
-- Matched: '[일반전형]광주전남본부 - 기술' -> '일반사무' (0.5285)
-- SKIPPED (low similarity 0.4832): '[일반전형]함평지사 - 기술' -> '현장·시공·감리·공무'
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 636;
-- Matched: '[일반전형]구례지사 - 행정' -> '현장·시공·감리·공무' (0.5339)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 637;
-- Matched: '[일반전형]보성지사 - 기술' -> '일반사무' (0.5019)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 638;
-- Matched: '[일반전형]남원지사 - 행정' -> '현장·시공·감리·공무' (0.5257)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 639;
-- Matched: '[일반전형]대구경북본부 - 행정' -> '일반사무' (0.5100)
-- SKIPPED (low similarity 0.4776): '[일반전형]대구경북본부 - 기술' -> '일반사무'
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 641;
-- Matched: '[일반전형]대구지사 - 행정' -> '현장·시공·감리·공무' (0.5535)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 642;
-- Matched: '[일반전형]대구지사 - 기술' -> '일반사무' (0.5179)
-- SKIPPED (low similarity 0.4648): '[일반전형]군위지사 - 기술' -> '총무'
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 644;
-- Matched: '[일반전형]영천지사 - 행정' -> '현장·시공·감리·공무' (0.5337)
-- SKIPPED (low similarity 0.4904): '[일반전형]영천지사 - 기술' -> '일반사무'
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 646;
-- Matched: '[일반전형]고령지사 - 행정' -> '현장·시공·감리·공무' (0.5302)
-- SKIPPED (low similarity 0.4627): '[일반전형]고령지사 - 기술' -> '현장·시공·감리·공무'
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 648;
-- Matched: '[일반전형]부산경남본부 - 행정' -> '일반사무' (0.5523)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 649;
-- Matched: '[일반전형]부산경남본부 - 기술' -> '일반사무' (0.5358)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 650;
-- Matched: '[일반전형]양산지사 - 기술' -> '일반사무' (0.5178)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 651;
-- Matched: '[일반전형]창원지사 - 행정' -> '일반사무' (0.5171)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 652;
-- Matched: '[일반전형]진주지사 - 행정' -> '현장·시공·감리·공무' (0.5466)
-- SKIPPED (low similarity 0.4932): '[일반전형]산청지사 - 기술' -> '현장·시공·감리·공무'
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 654;
-- Matched: '[일반전형]경주지사 - 행정' -> '현장·시공·감리·공무' (0.5532)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 655;
-- Matched: '[일반전형]창녕지사 - 행정' -> '현장·시공·감리·공무' (0.5086)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 656;
-- Matched: '[일반전형]고성지사 - 기술' -> '일반사무' (0.5089)
-- SKIPPED (low similarity 0.4771): '[일반전형]서울산지사 - 기술' -> '일반사무'
-- SKIPPED (low similarity 0.4790): '[일반전형]밀양지사 - 행정' -> '현장·시공·감리·공무'
-- SKIPPED (low similarity 0.4764): '[일반전형]밀양지사 - 기술' -> '일반사무'
-- SKIPPED (low similarity 0.4328): '[자립준비청년전형]전국권역' -> '채권·심사'
-- SKIPPED (low similarity 0.4411): '[다자녀가족전형]전국권역 - 행정' -> '현장·시공·감리·공무'
-- SKIPPED (low similarity 0.4152): '[다자녀가족전형]전국권역 - 기술' -> '채권·심사'
-- SKIPPED (low similarity 0.4550): '[사회형평전형]전국권역 - 행정' -> '현장·시공·감리·공무'
-- SKIPPED (low similarity 0.4239): '[사회형평전형]전국권역 - 기술' -> '통신기술·네트워크 구축'
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 666;
-- Matched: '[일반]사무' -> '일반사무' (0.8558)
UPDATE recruitment SET category_id = 162 WHERE recruitment_id = 667;
-- Matched: '[일반]기계' -> '기계' (0.6242)
UPDATE recruitment SET category_id = 177 WHERE recruitment_id = 668;
-- Matched: '[일반]전기' -> '전기·전자·제어' (0.6187)
UPDATE recruitment SET category_id = 165 WHERE recruitment_id = 669;
-- Matched: '[일반]화학' -> '화학' (0.6539)
UPDATE recruitment SET category_id = 135 WHERE recruitment_id = 670;
-- Matched: '[일반]ICT' -> '전기·통신' (0.5296)
UPDATE recruitment SET category_id = 139 WHERE recruitment_id = 671;
-- Matched: '[일반]토목' -> '토목·조경·도시' (0.6968)
UPDATE recruitment SET category_id = 199 WHERE recruitment_id = 672;
-- Matched: '[일반]건축' -> '건축·인테리어디자인' (0.6762)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 673;
-- Matched: '[보훈]사무' -> '일반사무' (0.5954)
UPDATE recruitment SET category_id = 162 WHERE recruitment_id = 674;
-- Matched: '[보훈]기계' -> '기계' (0.5266)
UPDATE recruitment SET category_id = 177 WHERE recruitment_id = 675;
-- Matched: '[보훈]전기' -> '전기·전자·제어' (0.5165)
UPDATE recruitment SET category_id = 165 WHERE recruitment_id = 676;
-- Matched: '[보훈]화학' -> '화학' (0.6127)
-- SKIPPED (low similarity 0.4756): '[보훈]ICT' -> '전기·통신'
UPDATE recruitment SET category_id = 139 WHERE recruitment_id = 678;
-- Matched: '[보훈]토목' -> '토목·조경·도시' (0.6383)
UPDATE recruitment SET category_id = 199 WHERE recruitment_id = 679;
-- Matched: '[보훈]건축' -> '건축·인테리어디자인' (0.6328)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 680;
-- Matched: '[장애]사무' -> '일반사무' (0.6133)
UPDATE recruitment SET category_id = 162 WHERE recruitment_id = 681;
-- Matched: '[장애]기계' -> '기계' (0.5293)
UPDATE recruitment SET category_id = 177 WHERE recruitment_id = 682;
-- Matched: '[장애]전기' -> '전기·전자·제어' (0.5230)
UPDATE recruitment SET category_id = 165 WHERE recruitment_id = 683;
-- Matched: '[장애]화학' -> '화학' (0.5486)
-- SKIPPED (low similarity 0.4537): '[장애]ICT' -> '전기·통신'
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 685;
-- Matched: '공간운영지원' -> '영업관리·지원·기획' (0.6141)
-- SKIPPED (low similarity 0.4883): '치공구개발 (주재원)' -> '프론트엔드개발'
-- SKIPPED (low similarity 0.3874): 'Costing' -> '결산'
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 688;
-- Matched: '설비개발' -> '생산·제조·설비·조립' (0.6169)
UPDATE recruitment SET category_id = 72 WHERE recruitment_id = 689;
-- Matched: '설계 자동화 개발' -> '안드로이드개발' (0.5305)
UPDATE recruitment SET category_id = 71 WHERE recruitment_id = 690;
-- Matched: '치공구개발' -> 'IOS개발' (0.5237)
UPDATE recruitment SET category_id = 203 WHERE recruitment_id = 691;
-- Matched: 'Visual Designer' -> 'UI·UX디자인' (0.5071)
UPDATE recruitment SET category_id = 197 WHERE recruitment_id = 692;
-- Matched: 'IE (산업공학)' -> '제품·산업디자인' (0.5591)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 693;
-- Matched: '생산계획' -> '생산관리' (0.7167)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 694;
-- Matched: '플랫폼개발 (TDS 파견)' -> '서버·백엔드개발' (0.5173)
UPDATE recruitment SET category_id = 5 WHERE recruitment_id = 695;
-- Matched: '정보전략' -> '경영전략' (0.6171)
UPDATE recruitment SET category_id = 17 WHERE recruitment_id = 696;
-- Matched: '재무' -> '재무' (1.0000)
-- SKIPPED (low similarity 0.4899): '건설지원' -> '설치·정비·AS·시공·공무'
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 698;
-- Matched: '경영기획' -> '경영기획' (1.0000)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 699;
-- Matched: '사업관리' -> '사업기획' (0.7525)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 700;
-- Matched: '프로젝트금융3실' -> '금융·보험영업' (0.5398)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 701;
-- Matched: '영업' -> '해외영업' (0.7247)
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 702;
-- Matched: '마케팅' -> '마케팅전략·기획' (0.7821)
UPDATE recruitment SET category_id = 81 WHERE recruitment_id = 703;
-- Matched: '데이터사이언스' -> '데이터분석' (0.6944)
-- SKIPPED (low similarity 0.4755): '[서울] 원가' -> '은행원'
UPDATE recruitment SET category_id = 59 WHERE recruitment_id = 705;
-- Matched: '[서울] 구매' -> '구매' (0.6694)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 706;
-- Matched: '[서울] 정보화관리' -> '안전관리' (0.5481)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 707;
-- Matched: '[서울] ESG경영' -> '경영기획' (0.5676)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 708;
-- Matched: '[서울] 해외영업' -> '해외영업' (0.7932)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 709;
-- Matched: '[서울] 해외영업(STS)' -> '해외영업' (0.6876)
UPDATE recruitment SET category_id = 50 WHERE recruitment_id = 710;
-- Matched: '[포항] 물류' -> '물류관리·기획' (0.6507)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 711;
-- Matched: '[포항] 품질관리' -> '품질관리' (0.7577)
UPDATE recruitment SET category_id = 197 WHERE recruitment_id = 712;
-- Matched: '[포항] 제품개발' -> '제품·산업디자인' (0.5849)
UPDATE recruitment SET category_id = 137 WHERE recruitment_id = 713;
-- Matched: '[포항] 설비-기계' -> '기계·설비·화학' (0.6217)
UPDATE recruitment SET category_id = 177 WHERE recruitment_id = 714;
-- Matched: '[포항] 설비-전기' -> '전기·전자·제어' (0.5726)
UPDATE recruitment SET category_id = 10 WHERE recruitment_id = 715;
-- Matched: '[포항] 인사/노무' -> '노무' (0.6134)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 716;
-- Matched: '[순천] 생산관리' -> '생산관리' (0.7269)
UPDATE recruitment SET category_id = 28 WHERE recruitment_id = 717;
-- Matched: '[순천] 노무/총무' -> '총무' (0.6577)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 718;
-- Matched: '[순천] 프로젝트 관리' -> '서비스기획·PM' (0.6132)
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 719;
-- Matched: '[창원] 생산기술' -> '생산·제조·설비·조립' (0.5766)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 720;
-- Matched: '[군산] 품질관리' -> '품질관리' (0.7299)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 721;
-- Matched: 'KNIT 해외영업(Academy sports)' -> '해외영업' (0.5659)
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 722;
-- Matched: '마케팅 기획' -> '마케팅전략·기획' (0.8986)
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 723;
-- Matched: '마케팅 데이터 분석' -> '마케팅전략·기획' (0.6639)
-- SKIPPED (low similarity 0.3748): '영상의학과-방사선사' -> '음악·영상·사진'
-- SKIPPED (low similarity 0.4654): '연구직_원자력통제' -> '안전관리'
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 726;
-- Matched: '행정직_전산' -> '일반사무' (0.5781)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 727;
-- Matched: '행정직_기획예산' -> '경영기획' (0.6446)
-- SKIPPED (low similarity 0.4724): '오퍼레이터' -> '무대·스탭·오퍼레이터'
UPDATE recruitment SET category_id = 37 WHERE recruitment_id = 729;
-- Matched: '콘텐츠 PD' -> '콘텐츠마케팅' (0.6767)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 888;
-- Matched: '창업지원 및 사업운영' -> '영업관리·지원·기획' (0.6305)
-- SKIPPED (low similarity 0.4857): '태양광사업' -> '사업기획'
UPDATE recruitment SET category_id = 20 WHERE recruitment_id = 732;
-- Matched: '자금/회계' -> '자금' (0.8130)
-- SKIPPED (low similarity 0.4766): '감사' -> '인사'
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 734;
-- Matched: 'SMR사업' -> '사업기획' (0.5312)
-- SKIPPED (low similarity 0.4521): 'Global Sales Intern' -> '해외영업'
UPDATE recruitment SET category_id = 36 WHERE recruitment_id = 736;
-- Matched: 'Brand Manager' -> '브랜드마케팅' (0.5500)
-- SKIPPED (low similarity 0.4715): '영상 크리에이터' -> '음악·영상·사진'
UPDATE recruitment SET category_id = 37 WHERE recruitment_id = 738;
-- Matched: '커머스 마케터' -> '콘텐츠마케팅' (0.6110)
-- SKIPPED (low similarity 0.3875): 'PV' -> 'IR'
-- SKIPPED (low similarity 0.4529): '게임플레이' -> '그래픽디자인·CG'
UPDATE recruitment SET category_id = 194 WHERE recruitment_id = 741;
-- Matched: 'AI, 캐릭터&애니메이션' -> '애니메이션' (0.6529)
-- SKIPPED (low similarity 0.3674): '렌더링' -> '채용'
-- SKIPPED (low similarity 0.4569): '게임플랫폼' -> '서버·백엔드개발'
UPDATE recruitment SET category_id = 72 WHERE recruitment_id = 744;
-- Matched: '모바일플랫폼' -> '안드로이드개발' (0.5390)
UPDATE recruitment SET category_id = 193 WHERE recruitment_id = 745;
-- Matched: '캐릭터 모델링' -> '캐릭터' (0.6191)
-- SKIPPED (low similarity 0.4905): '배경 모델링' -> '그래픽디자인·CG'
UPDATE recruitment SET category_id = 194 WHERE recruitment_id = 747;
-- Matched: '애니메이션' -> '애니메이션' (1.0000)
-- SKIPPED (low similarity 0.4463): '셰이더' -> '채용'
UPDATE recruitment SET category_id = 203 WHERE recruitment_id = 749;
-- Matched: '웹디자인/UI' -> 'UI·UX디자인' (0.8143)
UPDATE recruitment SET category_id = 191 WHERE recruitment_id = 750;
-- Matched: '게임 비주얼 콘셉트' -> '그래픽디자인·CG' (0.5233)
UPDATE recruitment SET category_id = 191 WHERE recruitment_id = 751;
-- Matched: '게임디자인(기획)' -> '그래픽디자인·CG' (0.5852)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 752;
-- Matched: '서비스디자인(웹기획)' -> '서비스기획·PM' (0.7187)
UPDATE recruitment SET category_id = 66 WHERE recruitment_id = 753;
-- Matched: '상품기획 및 개발 PM' -> '상품기획·MD' (0.7988)
-- SKIPPED (low similarity 0.3375): 'Vision's Edge Device Academy (VEDA) ' -> '비서'
UPDATE recruitment SET category_id = 6 WHERE recruitment_id = 755;
-- Matched: '경영분야-법무담당자-판교본사' -> '경영분석·컨설턴트' (0.5358)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 756;
-- Matched: '개발분야-백엔드 개발-판교본사' -> '서버·백엔드개발' (0.6683)
-- SKIPPED (low similarity 0.3827): '정규직(신규)-간호사-분만실' -> '현장·시공·감리·공무'
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 758;
-- Matched: 'IB솔루션2실' -> 'IT·솔루션·기술영업' (0.5981)
UPDATE recruitment SET category_id = 95 WHERE recruitment_id = 759;
-- Matched: 'ERP 서비스 운영' -> 'SW·솔루션·ERP' (0.5554)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 760;
-- Matched: '협업 서비스 두레이 온보딩 매니저' -> '서비스기획·PM' (0.5088)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 761;
-- Matched: '운영지원처_실무원(상담)_콜센터 전화상담' -> '영업관리·지원·기획' (0.5312)
-- SKIPPED (low similarity 0.4394): '모빌리티연구처_위촉연구원 6급_국가대중교통정보센터 운영 보조' -> '물류관리·기획'
-- SKIPPED (low similarity 0.4724): '모빌리티연구처_청년인턴(사무)_버스정보시스템 통합센터 운영 보조' -> '영업관리·지원·기획'
-- SKIPPED (low similarity 0.4345): '모빌리티연구처_청년인턴(사무)_교통약자 이동편의 실태조사 연구 지원(현황정리 및 조사)' -> '리서치·시장조사'
-- SKIPPED (low similarity 0.4432): '모빌리티연구처_청년인턴(사무)_국가교통안전기본계획 수립 연구 업무 지원' -> '영업관리·지원·기획'
UPDATE recruitment SET category_id = 80 WHERE recruitment_id = 766;
-- Matched: '데이터융복합처_청년인턴(사무)_운행기록 데이터 분석, 문서작성 등 사무 및 행정업무' -> '데이터엔지니어' (0.5196)
-- SKIPPED (low similarity 0.4807): '데이터융복합처_청년인턴(사무)_교통카드 데이터 분석, 문서작성 등 사무 및 행정업무' -> '데이터분석'
UPDATE recruitment SET category_id = 81 WHERE recruitment_id = 768;
-- Matched: '데이터융복합처_청년인턴(사무)_데이터·통계 분석 등 사무 및 문서 작성 업무' -> '데이터분석' (0.5206)
-- SKIPPED (low similarity 0.4411): '교통안전처_청년인턴(사무)_공익제보단 민원응대 및 부서 사무보조' -> '사회복지·요양보호·자원봉사'
-- SKIPPED (low similarity 0.4392): '교통안전처_청년인턴(사무)_지원 사업 수행 및 운수종사자격 민원 상담 등' -> '영업관리·지원·기획'
UPDATE recruitment SET category_id = 50 WHERE recruitment_id = 771;
-- Matched: '기후탄소물류처_위촉연구원6급_화물운송산업 정책 연구 및 행정 지원' -> '물류관리·기획' (0.6068)
-- SKIPPED (low similarity 0.4620): '탄소중립정책팀_위촉연구원6급_수송부문 탄소중립사업 연구보조(목표관리제)' -> '물류관리·기획'
-- SKIPPED (low similarity 0.4170): '탄소중립정책팀_위촉연구원6급_수송부문 탄소중립사업 연구보조(외부사업)' -> '물류관리·기획'
-- SKIPPED (low similarity 0.4756): '모빌리티지원센터_청년인턴(사무)_행정업무(모빌리티 지원센터 업무 보조)' -> '영업관리·지원·기획'
-- SKIPPED (low similarity 0.4783): '실증사업처_청년인턴(사무)_행정업무(교통안전 특별실태조사 업무 보조)' -> '사무보조'
-- SKIPPED (low similarity 0.4927): '검사기획처_청년인턴(사무)_행정업무(이륜자동차 업무 등 사무보조)' -> '사무보조'
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 777;
-- Matched: '첨단검사전략처_청년인턴(사무)_자동차검사 기술인력 교육 업무 보조' -> '사무보조' (0.5157)
-- SKIPPED (low similarity 0.4512): '기술안전처_청년인턴(사무)_운행 자동차 수시점검 지원 사업 회계업무 등' -> '안전관리'
-- SKIPPED (low similarity 0.4497): '항공안전처_위촉연구원6급_초경량비행장치 사고조사 업무 지원' -> '안전관리'
-- SKIPPED (low similarity 0.4905): '항공안전처_위촉연구원6급_항공안전 자율보고제도 업무 지원' -> '안전관리'
-- SKIPPED (low similarity 0.4702): '항공자격처_청년인턴(사무)_자격증발급 업무 및 항공종사자 자격시험 일반업무 보조' -> '일반사무'
-- SKIPPED (low similarity 0.4669): '드론관리처_위촉연구원6급_드론 안전 및 활성화 지원사업 업무 지원' -> '안전관리'
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 783;
-- Matched: '드론관리처_위촉연구원6급_운영계획 수립 및 문서작성 등 행정 업무' -> '경영기획' (0.5113)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 784;
-- Matched: '드론관리처_실무원(사무)_민원응대 및 행정 등' -> '현장·시공·감리·공무' (0.5239)
-- SKIPPED (low similarity 0.4848): '드론관리처_위촉연구원6급_시흥 초경량비행장치 사용 사업체 점검 업무 등' -> '설치·정비·AS·시공·공무'
-- SKIPPED (low similarity 0.4895): '드론관리처_위촉연구원6급_대구 초경량비행장치 사용 사업체 점검 업무 등' -> '설치·정비·AS·시공·공무'
-- SKIPPED (low similarity 0.4756): '드론관리처_위촉연구원6급_광주 초경량비행장치 사용 사업체 점검 업무 등' -> '설치·정비·AS·시공·공무'
-- SKIPPED (low similarity 0.4821): '드론관리처_청년인턴(사무)_행정 업무(드론안전 및 사업관리 사무보조)' -> '영업관리·지원·기획'
-- SKIPPED (low similarity 0.4656): '드론관리처_위촉연구원6급_행정 업무(드론 및 사업 사무보조)' -> '사무보조'
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 790;
-- Matched: '드론관리처_실무원(사무)_민원응대 및 사무보조 등' -> '사무보조' (0.5507)
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 791;
-- Matched: '드론관리처_실무원(사무)_민원응대 및 행정보조 등' -> '사무보조' (0.5156)
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 792;
-- Matched: '도심항공정책처_위촉연구원6급_용역수행을 위한 연구지원 및 사무보조' -> '사무보조' (0.5333)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 793;
-- Matched: '안전사업2처(서울)_실무원(사무)_행정업무(민원응대 및 교육 지원 등)' -> '안전관리' (0.5536)
-- SKIPPED (low similarity 0.4866): '강남검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
-- SKIPPED (low similarity 0.4718): '성산검사소_청년인턴(사무)_행정업무(검사접수 등)' -> '일반사무'
-- SKIPPED (low similarity 0.4551): '성산검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
-- SKIPPED (low similarity 0.4690): '노원검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
UPDATE recruitment SET category_id = 161 WHERE recruitment_id = 798;
-- Matched: '성동검사소_실무원(검사)_자동차 검사' -> '자동차' (0.5082)
-- SKIPPED (low similarity 0.4966): '안전사업처(경기남부)_청년인턴(사무)_행정업무(국가자격시험 보조 및 민원응대 등)' -> '안전관리'
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 800;
-- Matched: '안전사업처(경기남부)_청년인턴(사무_장애)_행정업무 등' -> '안전관리' (0.5002)
UPDATE recruitment SET category_id = 161 WHERE recruitment_id = 801;
-- Matched: '수원검사소_실무원(검사)_자동차 검사' -> '자동차' (0.5107)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 802;
-- Matched: '안양검사소_실무원(사무)_행정 및 자동차검사 접수 업무 등' -> '일반사무' (0.5115)
-- SKIPPED (low similarity 0.4907): '서수원검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
UPDATE recruitment SET category_id = 111 WHERE recruitment_id = 804;
-- Matched: '안산검사소_청년인턴(검사)_자동차 검사업무 보조' -> '설치·정비·AS·시공·공무' (0.5062)
-- SKIPPED (low similarity 0.4481): '동탄검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
-- SKIPPED (low similarity 0.4922): '용인검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
-- SKIPPED (low similarity 0.4546): '안전사업처(대전세종충남)_청년인턴(사무)_운전적성정밀검사 및 국가자격시험 등 사무보조' -> '안전관리'
-- SKIPPED (low similarity 0.4780): '안전사업처(대전세종충남) 또는 신탄진검사소_청년인턴(사무_장애)_사무보조 등' -> '안전관리'
-- SKIPPED (low similarity 0.4796): '대전검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
-- SKIPPED (low similarity 0.4511): '신탄진검사소_청년인턴(검사)_이륜차(출장 포함) 검사 및 자동차 검사 업무 보조' -> '현장·시공·감리·공무'
UPDATE recruitment SET category_id = 38 WHERE recruitment_id = 886;
-- Matched: '퍼포먼스 마케터(AE) (국내)' -> '퍼포먼스·온라인마케팅' (0.6834)
-- SKIPPED (low similarity 0.4415): '세종검사소_청년인턴(검사)_이륜차(출장 포함) 검사 및 자동차 검사 업무 보조' -> '현장·시공·감리·공무'
-- SKIPPED (low similarity 0.4749): '안전사업처(대구경북)_청년인턴(사무_장애)_사무보조 등' -> '사무보조'
-- SKIPPED (low similarity 0.4745): '수성검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
-- SKIPPED (low similarity 0.4898): '달서검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
-- SKIPPED (low similarity 0.4802): '포항검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 816;
-- Matched: '경주검사소_실무원(사무)_검사소 사무업무 등' -> '일반사무' (0.5912)
-- SKIPPED (low similarity 0.4766): '경주검사소_실무원(검사)_자동차 검사업무' -> '자동차'
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 818;
-- Matched: '경주검사소_청년인턴(사무_장애)_사무보조 등' -> '사무보조' (0.5469)
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 819;
-- Matched: '구미검사소_청년인턴(사무_장애)_사무보조 등' -> '사무보조' (0.5460)
-- SKIPPED (low similarity 0.4586): '구미검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
-- SKIPPED (low similarity 0.4675): '문경검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
-- SKIPPED (low similarity 0.4561): '해운대검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
UPDATE recruitment SET category_id = 161 WHERE recruitment_id = 823;
-- Matched: '해운대검사소_실무원(검사)_자동차 검사' -> '자동차' (0.5017)
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 824;
-- Matched: '사하검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조' (0.5139)
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 825;
-- Matched: '광주검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조' (0.5086)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 826;
-- Matched: '안전관리처(경기북부)_청년인턴(사무)_국가자격시험 업무보조' -> '안전관리' (0.5765)
-- SKIPPED (low similarity 0.4896): '남양주검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
UPDATE recruitment SET category_id = 106 WHERE recruitment_id = 828;
-- Matched: '안전관리처(인천)_실무원(환경)_환경미화' -> '환경관리' (0.6603)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 829;
-- Matched: '안전관리처(인천) 또는 서인천검사소_청년인턴(사무_장애)_사무보조, 민원응대 등' -> '안전관리' (0.5129)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 830;
-- Matched: '안전관리처(강원)_청년인턴(사무_장애)_민원응대 등 사무보조' -> '안전관리' (0.5463)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 831;
-- Matched: '안전관리처(강원)_청년인턴(사무)_국가자격시험 등 업무보조' -> '안전관리' (0.5693)
-- SKIPPED (low similarity 0.4917): '원주검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
-- SKIPPED (low similarity 0.4419): '태백검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 834;
-- Matched: '청주검사소_청년인턴(사무_장애)_사무보조 등' -> '사무보조' (0.5550)
-- SKIPPED (low similarity 0.4817): '청주검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 836;
-- Matched: '충주검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조' (0.5039)
-- SKIPPED (low similarity 0.4522): '전주검사소_청년인턴(검사)_이륜차(출장 포함) 검사 및 자동차 검사 업무 보조' -> '현장·시공·감리·공무'
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 838;
-- Matched: '안전관리처(경남)_청년인턴(사무_장애)_행정업무(민원응대 등 사무보조)' -> '안전관리' (0.5260)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 839;
-- Matched: '안전관리처(경남)_청년인턴(사무)_행정업무(국가자격시험 보조 및 민원응대 등)' -> '안전관리' (0.5502)
-- SKIPPED (low similarity 0.4771): '창원검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
-- SKIPPED (low similarity 0.4710): '진주검사소_청년인턴(검사)_자동차 검사업무 보조' -> '설치·정비·AS·시공·공무'
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 842;
-- Matched: '안전관리처(울산)_청년인턴(사무_장애)_행정업무 등' -> '안전관리' (0.5581)
-- SKIPPED (low similarity 0.4613): '울산검사소_청년인턴(검사)_자동차 검사업무 보조' -> '설치·정비·AS·시공·공무'
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 844;
-- Matched: '안전관리처(제주)_청년인턴(사무_장애)_민원응대 및 사무업무 보조' -> '안전관리' (0.5109)
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 845;
-- Matched: '제주검사소_청년인턴(사무_장애)_민원응대 및 사무 보조' -> '사무보조' (0.5386)
-- SKIPPED (low similarity 0.4743): '제주검사소_청년인턴(검사)_자동차 검사업무 보조' -> '사무보조'
-- SKIPPED (low similarity 0.4945): '화성드론자격센터_청년인턴(사무)_센터 운영 업무 보조 및 민원 응대' -> '영업관리·지원·기획'
UPDATE recruitment SET category_id = 38 WHERE recruitment_id = 887;
-- Matched: '퍼포먼스 마케터(AE) (글로벌(일본))' -> '퍼포먼스·온라인마케팅' (0.6345)
-- SKIPPED (low similarity 0.4146): '시흥드론교육센터_위촉연구원6급_드론 임무특화교육 사업 보조' -> '교육개발·기획'
UPDATE recruitment SET category_id = 106 WHERE recruitment_id = 849;
-- Matched: '시흥드론교육센터_실무원(환경)_환경미화' -> '환경관리' (0.5400)
-- SKIPPED (low similarity 0.4534): '김천드론자격센터_청년인턴(사무)_행정업무(자격시험 운영 및 행정서무 등)' -> '현장·시공·감리·공무'
-- SKIPPED (low similarity 0.4504): '결함조사1처_청년인턴(사무)_사고기록장치 안전기준 적합 시험 업무 지원 등' -> '현장·시공·감리·공무'
-- SKIPPED (low similarity 0.4433): '결함조사2처_청년인턴(사무)_자동차 화재조사 업무 지원 등' -> '영업관리·지원·기획'
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 853;
-- Matched: '안전연구처_청년인턴(사무)_자동차안전도평가 업무보조' -> '안전관리' (0.5129)
-- SKIPPED (low similarity 0.4355): '안전연구처_위촉연구원6급_전기차 배터리 안전성 평가 및 통합 안전기술 개발 연구' -> '안전관리'
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 855;
-- Matched: '안전연구처_실무원(사무)_자동차안전도평가 충돌시험 업무' -> '안전관리' (0.5137)
-- SKIPPED (low similarity 0.4753): '안전연구처_청년인턴(사무)_차량방호안전시설 성능시험 업무 보조' -> '안전관리'
-- SKIPPED (low similarity 0.4387): '미래차연구처_청년인턴(사무)_에너지소비효율 분야 제작결함조사(시험업무 보조)' -> '경영분석·컨설턴트'
-- SKIPPED (low similarity 0.4114): '미래차연구처_위촉연구원6급_전기차 에너지소비효율 실차시험 및 친환경 성능평가 보조' -> '환경관리'
-- SKIPPED (low similarity 0.4428): '미래차연구처_실무원(사무)_실내공기질 측정시험 및 전기차 에너지소비효율 측정 보조' -> '전기·전자·제어'
-- SKIPPED (low similarity 0.4667): '부품연구처_청년인턴(사무)_자동차안전연구' -> '안전관리'
-- SKIPPED (low similarity 0.4498): '자율주행연구처_위촉연구원6급_연구보조(실차 시뮬레이션 등) 및 예산 관리' -> '사무보조'
-- SKIPPED (low similarity 0.4801): '자율주행연구처_청년인턴(사무)_연구보조(안전성 평가기술 등) 및 예산 관리' -> '안전관리'
-- SKIPPED (low similarity 0.4583): '자율주행연구처_위촉연구원6급_연구보조(자율주행 리빙랩 등) 및 예산 관리' -> '사무보조'
-- SKIPPED (low similarity 0.4815): '자율주행연구처_청년인턴(사무)_연구보조(운영성과 평가 지원 및 예산 관리)' -> '영업관리·지원·기획'
-- SKIPPED (low similarity 0.4564): '자율주행연구처_청년인턴(사무)_연구보조(제작결함조사)' -> '품질관리'
-- SKIPPED (low similarity 0.3815): '커넥티드카연구처_위촉연구원6급_연구보조(자동차 사이버보안관리체계 인증 관련 등)' -> '시스템프로그래머'
-- SKIPPED (low similarity 0.4597): '커넥티드카연구처_청년인턴(사무)_연구보조(자율주행 데이터 수집 및 가공 등)' -> '리서치·시장조사'
-- SKIPPED (low similarity 0.4476): '자율주행실증처_청년인턴(사무)_연구보조(자율주행 가상시험환경 구축 R&D 등)' -> 'IT·솔루션·기술영업'
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 869;
-- Matched: '안전기준국제화센터_실무원(사무)_연구업무 보조 및 행정업무 등' -> '사무보조' (0.5207)
UPDATE recruitment SET category_id = 161 WHERE recruitment_id = 870;
-- Matched: '자동차인증처_실무원(사무)_정부위탁사업 및 자율주행자동차 안전운행 성능 확인 보조' -> '자동차' (0.5072)
-- SKIPPED (low similarity 0.4745): '자동차인증처_청년인턴(사무)_정부위탁사업(기술검토, 안전검사 등) 업무 보조' -> '자동차'
UPDATE recruitment SET category_id = 111 WHERE recruitment_id = 872;
-- Matched: '건설기계인증처_청년인턴(사무)_건설기계 업무 지원 등' -> '설치·정비·AS·시공·공무' (0.5216)
-- SKIPPED (low similarity 0.4406): '특장차인증센터_청년인턴(사무)_소규모 제작자 자기인증 등' -> '외국어·자격증·기술강사'
-- SKIPPED (low similarity 0.4157): '자동차안전하자심의위원회사무국_청년인턴(사무)_교환 제도 운영 및 위원회 운영 업무보조 등' -> '영업관리·지원·기획'
-- SKIPPED (low similarity 0.4406): '자동차안전하자심의위원회사무국_청년인턴(사무)_환불 제도 운영 및 위원회 운영 업무보조 등' -> '영업관리·지원·기획'
-- SKIPPED (low similarity 0.4606): '자율주행자동차사고조사위원회사무국_청년인턴(사무)_자율주행차 사고조사 및 연구 보조' -> '사무보조'
-- SKIPPED (low similarity 0.3794): 'Barista Support' -> '사무보조'
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 878;
-- Matched: '사무행정(일반직 5급-서울)' -> '일반사무' (0.5927)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 879;
-- Matched: '사무행정(일반직 5급-광주)' -> '일반사무' (0.5876)
-- SKIPPED (low similarity 0.4915): 'Global Strategy Manager' -> '마케팅전략·기획'
UPDATE recruitment SET category_id = 20 WHERE recruitment_id = 881;
-- Matched: '자금운용' -> '자금' (0.7483)
UPDATE recruitment SET category_id = 135 WHERE recruitment_id = 882;
-- Matched: 'IT전산' -> '전기·통신' (0.5052)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 883;
-- Matched: '일반관리' -> '안전관리' (0.7059)
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 884;
-- Matched: '마케팅 사무보조' -> '사무보조' (0.6718)
UPDATE recruitment SET category_id = 72 WHERE recruitment_id = 885;
-- Matched: 'S-개발자 4기' -> '안드로이드개발' (0.5473)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 889;
-- Matched: '[경영지원] 해외법인 관리/결산 채용연계형 ' -> '해외영업' (0.5418)
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 890;
-- Matched: '마케팅' -> '마케팅전략·기획' (0.7821)
-- SKIPPED (low similarity 0.4758): '[경영지원] 화장품 해외 인허가(RA) 채용연계형 인턴사원 모집' -> '해외영업'
UPDATE recruitment SET category_id = 17 WHERE recruitment_id = 892;
-- Matched: '재무전략팀' -> '재무' (0.6512)
UPDATE recruitment SET category_id = 38 WHERE recruitment_id = 893;
-- Matched: '아마존 PPC&퍼포먼스 마케팅' -> '퍼포먼스·온라인마케팅' (0.6450)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 894;
-- Matched: '주임(C1)_일반전형' -> '일반사무' (0.5067)
-- SKIPPED (low similarity 0.4620): '주임(C1)_장교전형' -> '초·중·고 교사'
UPDATE recruitment SET category_id = 126 WHERE recruitment_id = 896;
-- Matched: '[CS] 국내 CS 운영/관리 담당 채용연계형 인턴사원 모집' -> '고객응대·CS' (0.5283)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 897;
-- Matched: '금융상품운용실' -> '금융·보험영업' (0.6850)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 898;
-- Matched: '일반계약직(교목행정)' -> '일반사무' (0.5680)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 899;
-- Matched: '일반계약직(교내행사지원)' -> '영업관리·지원·기획' (0.5152)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 900;
-- Matched: '사업기획' -> '사업기획' (1.0000)
UPDATE recruitment SET category_id = 40 WHERE recruitment_id = 901;
-- Matched: '상품기획' -> '상품기획' (1.0000)
-- SKIPPED (low similarity 0.3959): 'Global Sales Strategy & Operations Sales Analyst' -> '마케팅전략·기획'
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 903;
-- Matched: '글로벌 영업 전략 리더 (Global Sales Strategy Leader)' -> '마케팅전략·기획' (0.5262)
UPDATE recruitment SET category_id = 43 WHERE recruitment_id = 904;
-- Matched: '마케팅(AE) ' -> '광고기획·AE' (0.6616)
UPDATE recruitment SET category_id = 43 WHERE recruitment_id = 905;
-- Matched: '마케팅(AE) 체험형 인턴' -> '광고기획·AE' (0.5694)
UPDATE recruitment SET category_id = 199 WHERE recruitment_id = 906;
-- Matched: '디자이너(Designer) 전환형 인턴' -> '건축·인테리어디자인' (0.5055)
UPDATE recruitment SET category_id = 114 WHERE recruitment_id = 907;
-- Matched: '기계사업본부 서비스부' -> '제품·서비스영업' (0.5845)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 908;
-- Matched: '고창공장 안전보건' -> '안전관리' (0.6087)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 909;
-- Matched: '영업기획' -> '사업기획' (0.8174)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 910;
-- Matched: '해외영업' -> '해외영업' (1.0000)
UPDATE recruitment SET category_id = 233 WHERE recruitment_id = 911;
-- Matched: '연구개발' -> '교육개발·기획' (0.5860)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 912;
-- Matched: '생산기획' -> '생산관리' (0.7655)
UPDATE recruitment SET category_id = 106 WHERE recruitment_id = 913;
-- Matched: '전기설비 관리' -> '환경관리' (0.6003)
UPDATE recruitment SET category_id = 91 WHERE recruitment_id = 914;
-- Matched: '[NHN Cloud] AI 전환 백엔드 개발' -> '빅데이터·AI' (0.5592)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 915;
-- Matched: '사업팀 인턴' -> '사업기획' (0.5927)
UPDATE recruitment SET category_id = 9 WHERE recruitment_id = 916;
-- Matched: '인사실' -> '인사' (0.7428)
UPDATE recruitment SET category_id = 43 WHERE recruitment_id = 917;
-- Matched: '마케팅 영상 크리에이터(안다르 일본)' -> '광고기획·AE' (0.5045)
-- SKIPPED (low similarity 0.4573): 'Strategy Product Manager' -> '마케팅전략·기획'
-- SKIPPED (low similarity 0.4897): '소프트웨어 테스팅' -> '응용프로그래머'
UPDATE recruitment SET category_id = 203 WHERE recruitment_id = 920;
-- Matched: '피그마 UI 실무' -> 'UI·UX디자인' (0.5369)
UPDATE recruitment SET category_id = 203 WHERE recruitment_id = 921;
-- Matched: 'UX/UI 디자인' -> 'UI·UX디자인' (0.8988)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 922;
-- Matched: '핀테크 서비스 기획' -> '서비스기획·PM' (0.6131)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 923;
-- Matched: '초보 PM 현업 가이드' -> '서비스기획·PM' (0.5020)
UPDATE recruitment SET category_id = 81 WHERE recruitment_id = 924;
-- Matched: '캐글 데이터 분석' -> '데이터분석' (0.6102)
UPDATE recruitment SET category_id = 75 WHERE recruitment_id = 925;
-- Matched: '프론트엔드 실무' -> '프론트엔드개발' (0.7891)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 926;
-- Matched: '웹 개발 완벽가이드' -> '서버·백엔드개발' (0.5192)
UPDATE recruitment SET category_id = 91 WHERE recruitment_id = 927;
-- Matched: 'AI 챗봇 구축' -> '빅데이터·AI' (0.5085)
UPDATE recruitment SET category_id = 91 WHERE recruitment_id = 928;
-- Matched: 'MLOps와 온디바이스 AI' -> '빅데이터·AI' (0.6033)
-- SKIPPED (low similarity 0.4659): '실전 DevOps 입문' -> '서버·백엔드개발'
-- SKIPPED (low similarity 0.4443): '실전완성 AWS 클라우드' -> '서버·백엔드개발'
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 931;
-- Matched: '해외영업' -> '해외영업' (1.0000)
UPDATE recruitment SET category_id = 60 WHERE recruitment_id = 932;
-- Matched: '자재구매 총무관리' -> '자재' (0.5931)
UPDATE recruitment SET category_id = 24 WHERE recruitment_id = 933;
-- Matched: '회계관리' -> '회계' (0.7783)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 934;
-- Matched: '대구경영업' -> '영업관리·지원·기획' (0.5242)
UPDATE recruitment SET category_id = 29 WHERE recruitment_id = 935;
-- Matched: '임원비서' -> '비서' (0.5036)
UPDATE recruitment SET category_id = 197 WHERE recruitment_id = 936;
-- Matched: '제품개발 기술개발' -> '제품·산업디자인' (0.6778)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 937;
-- Matched: '사무행정' -> '일반사무' (0.6871)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 938;
-- Matched: '생산관리 생산기술' -> '생산관리' (0.8443)
UPDATE recruitment SET category_id = 137 WHERE recruitment_id = 939;
-- Matched: '설비_공무/기계' -> '기계·설비·화학' (0.6485)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 940;
-- Matched: '품질보증(팀장급)' -> '품질관리' (0.6344)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 941;
-- Matched: '품질보증(팀원급)' -> '품질관리' (0.5978)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 942;
-- Matched: '품질관리' -> '품질관리' (1.0000)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 943;
-- Matched: '시스템관리' -> '안전관리' (0.6720)
-- SKIPPED (low similarity 0.4638): 'IT infra Management' -> '네트워크·보안·운영'
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 945;
-- Matched: '기술영업/마케팅' -> 'IT·솔루션·기술영업' (0.6082)
UPDATE recruitment SET category_id = 101 WHERE recruitment_id = 946;
-- Matched: '공정개발' -> '공정관리' (0.7261)
-- SKIPPED (low similarity 0.4467): '기구설계' -> '기계설계·CAD·CAM'
-- SKIPPED (low similarity 0.4440): '전장 설계' -> '광고 디자인'
UPDATE recruitment SET category_id = 175 WHERE recruitment_id = 949;
-- Matched: 'CAE(Computed Aided Engineering)' -> '기계설계·CAD·CAM' (0.5862)
-- SKIPPED (low similarity 0.4737): '요소기술개발' -> 'IT·솔루션·기술영업'
-- SKIPPED (low similarity 0.3560): 'sw' -> '운전'
UPDATE recruitment SET category_id = 59 WHERE recruitment_id = 952;
-- Matched: '구매관리' -> '구매' (0.7150)
UPDATE recruitment SET category_id = 5 WHERE recruitment_id = 953;
-- Matched: '전략개발구매' -> '경영전략' (0.6196)
-- SKIPPED (low similarity 0.3379): 'PEE' -> 'QA'
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 955;
-- Matched: '[대학내일] 마케팅(AE)_마케팅커뮤니케이션2팀_신입/경력(전환형)' -> '마케팅전략·기획' (0.5609)
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 956;
-- Matched: '[대학내일] 마케팅(AE)_마케팅커뮤니케이션3팀_인턴(전환형)' -> '마케팅전략·기획' (0.5008)
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 957;
-- Matched: '[대학내일] 마케팅(AE)_비즈니스임팩트1팀_인턴(체험형)' -> '마케팅전략·기획' (0.5127)
UPDATE recruitment SET category_id = 43 WHERE recruitment_id = 958;
-- Matched: '[대학내일] 마케팅(AE)_20대연구소_인턴(체험형)' -> '광고기획·AE' (0.5224)
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 959;
-- Matched: '[대학내일] 마케팅(AE)_마케팅커뮤니케이션4팀_인턴(체험형)' -> '마케팅전략·기획' (0.5109)
UPDATE recruitment SET category_id = 43 WHERE recruitment_id = 960;
-- Matched: '[대학내일] 마케팅(AE)_익스피리언스플래닝4팀_인턴(체험형)' -> '광고기획·AE' (0.5160)
UPDATE recruitment SET category_id = 37 WHERE recruitment_id = 961;
-- Matched: '[대학내일] 콘텐츠(에디터)_마케팅커뮤니케이션1팀_인턴(체험형)' -> '콘텐츠마케팅' (0.5576)
-- SKIPPED (low similarity 0.4969): '[51percent] 디자이너(Design)_크리에이티브팀_인턴(체험형)' -> '건축·인테리어디자인'
-- SKIPPED (low similarity 0.4989): 'Blockchain 개발자/컨설턴트 채용 (Frontend · Backend) 신입/경력' -> '서버·백엔드개발'
UPDATE recruitment SET category_id = 203 WHERE recruitment_id = 964;
-- Matched: '기구개발 및 설계' -> 'UI·UX디자인' (0.5877)
-- SKIPPED (low similarity 0.4904): '[삼일회계법인] 생성형 AI & AX 개발자/컨설턴트 채용(Frontend · Backend · AI R&D)' -> '빅데이터·AI'
UPDATE recruitment SET category_id = 28 WHERE recruitment_id = 966;
-- Matched: '경영지원/총무' -> '총무' (0.6223)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 967;
-- Matched: '영업' -> '해외영업' (0.7247)
UPDATE recruitment SET category_id = 46 WHERE recruitment_id = 968;
-- Matched: '대외협력·홍보' -> '사내홍보' (0.6664)
UPDATE recruitment SET category_id = 40 WHERE recruitment_id = 969;
-- Matched: '상품·서비스기획' -> '상품기획' (0.8617)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 970;
-- Matched: '전략기획' -> '사업기획' (0.7627)
UPDATE recruitment SET category_id = 9 WHERE recruitment_id = 971;
-- Matched: '인사기획' -> '인사' (0.6816)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 972;
-- Matched: '디지털채널영업' -> '해외영업' (0.5198)
-- SKIPPED (low similarity 0.4825): 'eSIM로밍사업 ' -> '해외영업'
UPDATE recruitment SET category_id = 89 WHERE recruitment_id = 974;
-- Matched: 'IT개발·운영관리' -> '네트워크·보안·운영' (0.6393)
UPDATE recruitment SET category_id = 227 WHERE recruitment_id = 975;
-- Matched: '정보보호' -> '보안·경비·경호' (0.5809)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 976;
-- Matched: '본사 비서실-기획비서' -> '영업관리·지원·기획' (0.6632)
UPDATE recruitment SET category_id = 50 WHERE recruitment_id = 1060;
-- Matched: '물류(신입)' -> '물류관리·기획' (0.6758)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 977;
-- Matched: '본사 비서실-수행비서' -> '일반사무' (0.5867)
UPDATE recruitment SET category_id = 203 WHERE recruitment_id = 978;
-- Matched: 'UI/UX' -> 'UI·UX디자인' (0.8003)
-- SKIPPED (low similarity 0.3796): 'DevSecOps(CI/CD)' -> '네트워크·보안·운영'
-- SKIPPED (low similarity 0.3233): 'Web3 Front-end' -> 'UI·UX디자인'
-- SKIPPED (low similarity 0.4554): 'Web3 Back-end' -> '서버·백엔드개발'
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 982;
-- Matched: 'Full Stack(PM)' -> '서비스기획·PM' (0.5042)
UPDATE recruitment SET category_id = 71 WHERE recruitment_id = 983;
-- Matched: 'iOS 개발' -> 'IOS개발' (0.9162)
UPDATE recruitment SET category_id = 72 WHERE recruitment_id = 984;
-- Matched: 'Android 개발' -> '안드로이드개발' (0.8619)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 985;
-- Matched: 'Back-end' -> '서버·백엔드개발' (0.5859)
-- SKIPPED (low similarity 0.4286): 'DevOps' -> 'DBA'
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 987;
-- Matched: '전략(전략기획)' -> '마케팅전략·기획' (0.6704)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 988;
-- Matched: '글로벌지원(글로벌사업 지원 및 기획)' -> '영업관리·지원·기획' (0.6659)
UPDATE recruitment SET category_id = 40 WHERE recruitment_id = 989;
-- Matched: '상품(디지털자산 상품기획)' -> '상품기획' (0.7679)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 990;
-- Matched: '경영기획(전략기획)' -> '경영기획' (0.8852)
UPDATE recruitment SET category_id = 33 WHERE recruitment_id = 991;
-- Matched: '법무(법률검토, 소송수행/관리)' -> '법무' (0.7421)
UPDATE recruitment SET category_id = 227 WHERE recruitment_id = 992;
-- Matched: '정보보호(정보보호담당)' -> '보안·경비·경호' (0.5373)
UPDATE recruitment SET category_id = 9 WHERE recruitment_id = 993;
-- Matched: '인사(채용)' -> '인사' (0.7133)
-- SKIPPED (low similarity 0.4582): '케미컬 개발 연구' -> '교육개발·기획'
-- SKIPPED (low similarity 0.4940): '[한미약품]의료정책교육' -> '바이오·제약'
-- SKIPPED (low similarity 0.4698): '[한미약품]청구' -> '상품기획·MD'
UPDATE recruitment SET category_id = 171 WHERE recruitment_id = 997;
-- Matched: '[한미약품]Medical' -> '바이오·제약' (0.5753)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 998;
-- Matched: '[한미약품]사업개발' -> '해외영업' (0.5707)
UPDATE recruitment SET category_id = 171 WHERE recruitment_id = 999;
-- Matched: '[한미약품]Regulatory Affairs' -> '바이오·제약' (0.5206)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 1000;
-- Matched: '[한미약품]해외영업' -> '해외영업' (0.7448)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 1001;
-- Matched: '[한미약품]해외영업기획' -> '해외영업' (0.6851)
UPDATE recruitment SET category_id = 59 WHERE recruitment_id = 1002;
-- Matched: '[한미약품]구매' -> '구매' (0.5852)
UPDATE recruitment SET category_id = 171 WHERE recruitment_id = 1003;
-- Matched: '[한미약품]R&D센터_C&G연구' -> '바이오·제약' (0.5112)
-- SKIPPED (low similarity 0.4828): '[한미약품]R&D센터_단백체 분석 연구' -> '바이오·제약'
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 1005;
-- Matched: '[한미약품]팔탄제조본부_생산관리' -> '생산·제조·설비·조립' (0.5356)
-- SKIPPED (low similarity 0.4530): '[한미약품]팔탄제조본부_기술지원' -> '생산·제조·설비·조립'
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 1007;
-- Matched: '[한미약품]팔탄제조본부_품질관리' -> '품질관리' (0.6261)
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 1008;
-- Matched: '[한미약품]팔탄제조본부_시설지원' -> '생산·제조·설비·조립' (0.5058)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 1009;
-- Matched: '[한미약품]평택제조본부_품질보증' -> '품질관리' (0.5292)
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 1010;
-- Matched: '[한미약품]팔탄제조본부_생산' -> '생산·제조·설비·조립' (0.5404)
-- SKIPPED (low similarity 0.4394): '[한미사이언스]Licensing' -> '해외영업'
-- SKIPPED (low similarity 0.4182): '[한미사이언스]재경' -> '재무'
-- SKIPPED (low similarity 0.3541): '[한미사이언스]컴플라이언스' -> '빅데이터·AI'
-- SKIPPED (low similarity 0.4925): '[한미사이언스]보안' -> '네트워크·보안·운영'
-- SKIPPED (low similarity 0.4409): '[한미사이언스]CSV' -> '빅데이터·AI'
UPDATE recruitment SET category_id = 241 WHERE recruitment_id = 1016;
-- Matched: '[한미사이언스]식품영업' -> '음식서비스' (0.5427)
UPDATE recruitment SET category_id = 133 WHERE recruitment_id = 1017;
-- Matched: '[한미사이언스]식품품질관리' -> '안전·품질·관리' (0.6401)
UPDATE recruitment SET category_id = 171 WHERE recruitment_id = 1018;
-- Matched: '[한미사이언스]의료기기마케팅' -> '바이오·제약' (0.5178)
UPDATE recruitment SET category_id = 171 WHERE recruitment_id = 1019;
-- Matched: '[한미사이언스]의료기기영업' -> '바이오·제약' (0.5354)
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 1020;
-- Matched: '[한미사이언스]생산' -> '생산·제조·설비·조립' (0.6013)
UPDATE recruitment SET category_id = 50 WHERE recruitment_id = 1021;
-- Matched: '[한미사이언스]물류운영관리' -> '물류관리·기획' (0.7075)
UPDATE recruitment SET category_id = 38 WHERE recruitment_id = 1022;
-- Matched: '퍼포먼스 마케터' -> '퍼포먼스·온라인마케팅' (0.7822)
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 1023;
-- Matched: 'IB솔루션3실' -> 'IT·솔루션·기술영업' (0.6077)
-- SKIPPED (low similarity 0.4502): '법인주식파생실' -> 'B2B영업·법인영업'
UPDATE recruitment SET category_id = 80 WHERE recruitment_id = 1025;
-- Matched: '데이터 엔지니어 (Google Analytics)' -> '데이터엔지니어' (0.7968)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 1026;
-- Matched: '일반직 - 일반' -> '일반사무' (0.6140)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 1027;
-- Matched: '일반직 - 보훈(제한경쟁)' -> '일반사무' (0.5010)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 1028;
-- Matched: '전산직 - 일반' -> '일반사무' (0.5951)
-- SKIPPED (low similarity 0.3852): '수영' -> '교육'
-- SKIPPED (low similarity 0.4860): '종합상황실' -> '안전관리'
UPDATE recruitment SET category_id = 63 WHERE recruitment_id = 1031;
-- Matched: '운전(준고령자)' -> '운전' (0.5667)
UPDATE recruitment SET category_id = 9 WHERE recruitment_id = 1032;
-- Matched: '안내' -> '인사' (0.6114)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 1033;
-- Matched: '일반행정(청년인턴/장애인)' -> '일반사무' (0.5478)
-- SKIPPED (low similarity 0.4828): 'Production Operator' -> '무대·스탭·오퍼레이터'
UPDATE recruitment SET category_id = 225 WHERE recruitment_id = 1035;
-- Matched: '정규직_재무(회계사)' -> '회계·세무·CPA·CFA' (0.6479)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 1036;
-- Matched: '정규직_사업개발(인프라·플랜트·도시개발)_3급' -> '사업기획' (0.5264)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 1037;
-- Matched: '정규직_사업개발(인프라·플랜트·도시개발)_4급' -> '사업기획' (0.5291)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 1038;
-- Matched: '정규직_금융·리스크' -> '금융·보험영업' (0.6145)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 1039;
-- Matched: '정규직_일반' -> '일반사무' (0.5981)
UPDATE recruitment SET category_id = 80 WHERE recruitment_id = 1040;
-- Matched: '정규직_전산(IT)' -> '데이터엔지니어' (0.5068)
-- SKIPPED (low similarity 0.4765): '원료/정제(신입)' -> '식품'
-- SKIPPED (low similarity 0.4957): '정규직_보훈' -> '현장·시공·감리·공무'
UPDATE recruitment SET category_id = 6 WHERE recruitment_id = 1042;
-- Matched: '계약직_도시컨설팅(전문계약직)' -> '경영분석·컨설턴트' (0.5841)
-- SKIPPED (low similarity 0.4913): '계약직_비서(육아휴직대체)' -> '사무보조'
-- SKIPPED (low similarity 0.4648): '계약직_정보보안(육아휴직대체)' -> '보안·경비·경호'
-- SKIPPED (low similarity 0.4291): '청년인턴(체험형)' -> '사내홍보'
-- SKIPPED (low similarity 0.4883): '통상팀 인턴 사원' -> '일반사무'
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 1047;
-- Matched: '생산 관리자' -> '생산관리' (0.8042)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 1048;
-- Matched: '부동산금융본부 ' -> '금융·보험영업' (0.5945)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 1049;
-- Matched: '리스크관리실' -> '안전관리' (0.5959)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 1050;
-- Matched: '여객영업(OTA 및 상용)' -> 'B2B영업·법인영업' (0.5541)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 1051;
-- Matched: '여객영업' -> '해외영업' (0.5455)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 1052;
-- Matched: '여객영업(Revenue Mamagement)' -> '영업관리·지원·기획' (0.5245)
UPDATE recruitment SET category_id = 17 WHERE recruitment_id = 1053;
-- Matched: '재무회계' -> '재무' (0.7333)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 1054;
-- Matched: '경영관리' -> '경영기획' (0.7854)
-- SKIPPED (low similarity 0.4694): '정비사' -> '비서'
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 1056;
-- Matched: '부품수리' -> '생산·제조·설비·조립' (0.5263)
-- SKIPPED (low similarity 0.4767): '정비 전문강사' -> '초·중·고 교사'
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 1058;
-- Matched: '영업추진실' -> '영업관리·지원·기획' (0.7128)
UPDATE recruitment SET category_id = 23 WHERE recruitment_id = 1059;
-- Matched: '경리(신입)' -> '경리' (0.7361)
-- SKIPPED (low similarity 0.4127): '이물검사(계약직)' -> '현장·시공·감리·공무'
-- SKIPPED (low similarity 0.4141): 'PV(Pharmacovigilance) 책임자' -> '안전관리'
-- SKIPPED (low similarity 0.4031): 'RA' -> 'QA'

-- Total Updated: 616
