-- Generated by match_recruitment_category.py
-- Date: 2026-02-02 14:56:21

UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 1;
-- Matched: '병의원 영업' -> 'B2B영업·법인영업' (0.5053)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 2;
-- Matched: '병의원 영업' -> 'B2B영업·법인영업' (0.5053)
UPDATE recruitment SET category_id = 75 WHERE recruitment_id = 3;
-- Matched: '프레임워크 개발' -> '프론트엔드개발' (0.6097)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 4;
-- Matched: '이물검사(계약직)' -> '현장·시공·감리·공무' (0.4127)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 5;
-- Matched: '품질경영 및 보증' -> '품질관리' (0.7881)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 6;
-- Matched: '품질보증(신입)' -> '품질관리' (0.5816)
UPDATE recruitment SET category_id = 46 WHERE recruitment_id = 7;
-- Matched: 'HR팀' -> '사내홍보' (0.4952)
UPDATE recruitment SET category_id = 40 WHERE recruitment_id = 8;
-- Matched: '안성쿠팡2센터' -> '상품기획' (0.4647)
UPDATE recruitment SET category_id = 6 WHERE recruitment_id = 9;
-- Matched: '클라우드 솔루션 아키텍트(SA) 컨설턴트' -> '경영분석·컨설턴트' (0.5311)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 10;
-- Matched: '병의원 영업' -> 'B2B영업·법인영업' (0.5053)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 11;
-- Matched: '병의원 영업' -> 'B2B영업·법인영업' (0.5053)
UPDATE recruitment SET category_id = 66 WHERE recruitment_id = 12;
-- Matched: 'ETC 영업 MR' -> '상품기획·MD' (0.5416)
UPDATE recruitment SET category_id = 38 WHERE recruitment_id = 13;
-- Matched: 'E-commerce Performance Media Assistant' -> '퍼포먼스·온라인마케팅' (0.5118)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 14;
-- Matched: '공장[안전보건]' -> '안전관리' (0.6043)
UPDATE recruitment SET category_id = 197 WHERE recruitment_id = 15;
-- Matched: '연구소[제품기술기획]' -> '제품·산업디자인' (0.5864)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 16;
-- Matched: '영업관리[영업소]' -> '영업관리·지원·기획' (0.7493)
UPDATE recruitment SET category_id = 219 WHERE recruitment_id = 17;
-- Matched: '연구소[건강기능식품 및 소재 개발]' -> '리서치·시장조사' (0.4805)
UPDATE recruitment SET category_id = 219 WHERE recruitment_id = 18;
-- Matched: '연구소[수출용 제품 개발 연구원]' -> '리서치·시장조사' (0.5274)
UPDATE recruitment SET category_id = 18 WHERE recruitment_id = 19;
-- Matched: '세무관리' -> '세무' (0.7632)
UPDATE recruitment SET category_id = 20 WHERE recruitment_id = 20;
-- Matched: '자금관리' -> '자금' (0.7479)
UPDATE recruitment SET category_id = 40 WHERE recruitment_id = 21;
-- Matched: '포장(경력)' -> '상품기획' (0.4342)
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 22;
-- Matched: '전기차 보조금 업무 사무보조 (장애인 제한경쟁)' -> '사무보조' (0.4875)
UPDATE recruitment SET category_id = 19 WHERE recruitment_id = 23;
-- Matched: 'IT' -> 'IR' (0.5281)
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 24;
-- Matched: 'Luxe - Marketing' -> '마케팅전략·기획' (0.4504)
UPDATE recruitment SET category_id = 59 WHERE recruitment_id = 25;
-- Matched: 'Luxe - E-Commerce/Sales' -> '구매' (0.3954)
UPDATE recruitment SET category_id = 95 WHERE recruitment_id = 26;
-- Matched: 'Luxe - CRM' -> 'SW·솔루션·ERP' (0.3569)
UPDATE recruitment SET category_id = 45 WHERE recruitment_id = 27;
-- Matched: 'Luxe - PR/Communication' -> '언론홍보·PR' (0.4865)
UPDATE recruitment SET category_id = 82 WHERE recruitment_id = 28;
-- Matched: 'LDB  - E-Commerce/Sales' -> 'DBA' (0.4558)
UPDATE recruitment SET category_id = 45 WHERE recruitment_id = 29;
-- Matched: 'CPD - PR/Communication' -> '언론홍보·PR' (0.5153)
UPDATE recruitment SET category_id = 66 WHERE recruitment_id = 30;
-- Matched: 'CPD - E-Commerce/Sales' -> '상품기획·MD' (0.3695)
UPDATE recruitment SET category_id = 66 WHERE recruitment_id = 31;
-- Matched: 'PPD - Marketing' -> '상품기획·MD' (0.4928)
UPDATE recruitment SET category_id = 66 WHERE recruitment_id = 32;
-- Matched: 'PPD - E-Commerce/Sales' -> '상품기획·MD' (0.4264)
UPDATE recruitment SET category_id = 66 WHERE recruitment_id = 33;
-- Matched: 'DMI - Marketing' -> '상품기획·MD' (0.4851)
UPDATE recruitment SET category_id = 66 WHERE recruitment_id = 34;
-- Matched: 'DMI - KIC - Marketing' -> '상품기획·MD' (0.4888)
UPDATE recruitment SET category_id = 66 WHERE recruitment_id = 35;
-- Matched: 'DMI - KIC - Innovation Packaging' -> '상품기획·MD' (0.4310)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 36;
-- Matched: 'CORP - Finance' -> '금융·보험영업' (0.4469)
UPDATE recruitment SET category_id = 95 WHERE recruitment_id = 37;
-- Matched: 'CORP - Operation - Sourcing' -> 'SW·솔루션·ERP' (0.3524)
UPDATE recruitment SET category_id = 82 WHERE recruitment_id = 38;
-- Matched: 'CORP - Operation - ODES' -> 'DBA' (0.3599)
UPDATE recruitment SET category_id = 190 WHERE recruitment_id = 39;
-- Matched: '캠페인플래닝' -> '광고 디자인' (0.5882)
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 40;
-- Matched: '접합재료(Solder)국내영업_용인' -> 'IT·솔루션·기술영업' (0.4706)
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 41;
-- Matched: '접합재료(Solder)국내영업_용인' -> 'IT·솔루션·기술영업' (0.4706)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 42;
-- Matched: '접합재료(Solder)국내영업_구미' -> '해외영업' (0.4668)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 43;
-- Matched: '접합재료(Solder)국내영업_구미' -> '해외영업' (0.4668)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 44;
-- Matched: 'OLED합성' -> '반도체·디스플레이' (0.5350)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 45;
-- Matched: 'OLED합성' -> '반도체·디스플레이' (0.5350)
UPDATE recruitment SET category_id = 208 WHERE recruitment_id = 46;
-- Matched: 'KB IT's Your Life 7기' -> '음악·영상·사진' (0.3762)
UPDATE recruitment SET category_id = 38 WHERE recruitment_id = 47;
-- Matched: '퍼포먼스 마케터' -> '퍼포먼스·온라인마케팅' (0.7823)
UPDATE recruitment SET category_id = 36 WHERE recruitment_id = 48;
-- Matched: '브랜드 마케터' -> '브랜드마케팅' (0.7870)
UPDATE recruitment SET category_id = 28 WHERE recruitment_id = 49;
-- Matched: '총무지원 매니저' -> '총무' (0.6838)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 50;
-- Matched: '카셰어링 사업 매니저(호남)' -> '해외영업' (0.4950)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 51;
-- Matched: '[PM] 앱 서비스 기획(채용연계형)' -> '서비스기획·PM' (0.6827)
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 52;
-- Matched: '[마케팅] 유럽 틱톡샵 마케팅 채용연계형 인턴 및 경력사원 모집(독일/스페인/프랑스/이탈리아)' -> '마케팅전략·기획' (0.4211)
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 53;
-- Matched: '[마케팅] 유럽 틱톡샵 마케팅 채용연계형 인턴 및 경력사원 모집(독일/스페인/프랑스/이탈리아)' -> '마케팅전략·기획' (0.4203)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 54;
-- Matched: '행정 부문' -> '현장·시공·감리·공무' (0.5716)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 55;
-- Matched: '행정 부문(지역우수인재)' -> '현장·시공·감리·공무' (0.5151)
UPDATE recruitment SET category_id = 227 WHERE recruitment_id = 56;
-- Matched: '정보보안 부문' -> '보안·경비·경호' (0.6633)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 57;
-- Matched: '웰빙사업팀-수도권영업담당' -> '영업관리·지원·기획' (0.5478)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 58;
-- Matched: '웰빙사업팀-지방영업담당' -> '영업관리·지원·기획' (0.5536)
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 59;
-- Matched: '제약마케팅팀-제약기획담당' -> '마케팅전략·기획' (0.6358)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 60;
-- Matched: '제약영업관리팀-제약영업관리담당' -> '영업관리·지원·기획' (0.6089)
UPDATE recruitment SET category_id = 171 WHERE recruitment_id = 61;
-- Matched: '의약연구실-개발담당' -> '바이오·제약' (0.5297)
UPDATE recruitment SET category_id = 101 WHERE recruitment_id = 62;
-- Matched: '초정공장-초정조제담당' -> '공정관리' (0.5135)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 63;
-- Matched: '서비스 매니저' -> '서비스기획·PM' (0.7263)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 64;
-- Matched: '서비스 매니저' -> '서비스기획·PM' (0.7263)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 65;
-- Matched: '테크니컬 라이터' -> '반도체·디스플레이' (0.3977)
UPDATE recruitment SET category_id = 6 WHERE recruitment_id = 66;
-- Matched: 'GEO 컨설턴트 (Junior)' -> '경영분석·컨설턴트' (0.5720)
UPDATE recruitment SET category_id = 37 WHERE recruitment_id = 67;
-- Matched: '[대학내일] 에디터_콘텐츠크리에이티브3팀_인턴(체험형)' -> '콘텐츠마케팅' (0.4155)
UPDATE recruitment SET category_id = 192 WHERE recruitment_id = 68;
-- Matched: '[대학내일] 에디터(자사미디어)_미디어센터_인턴(체험형)' -> '출판·편집디자인' (0.4358)
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 69;
-- Matched: '[대학내일] 마케팅(AE)_마케팅커뮤니케이션9팀_인턴(체험형)' -> '마케팅전략·기획' (0.5079)
UPDATE recruitment SET category_id = 43 WHERE recruitment_id = 70;
-- Matched: '[대학내일] 마케팅(AE)_익스피리언스플래닝4팀_경력(전환형)' -> '광고기획·AE' (0.5051)
UPDATE recruitment SET category_id = 167 WHERE recruitment_id = 71;
-- Matched: '상경' -> '환경' (0.5827)
UPDATE recruitment SET category_id = 199 WHERE recruitment_id = 72;
-- Matched: '건축' -> '건축·인테리어디자인' (0.7106)
UPDATE recruitment SET category_id = 148 WHERE recruitment_id = 73;
-- Matched: '자산운용/리스크' -> '증권·투자' (0.5571)
UPDATE recruitment SET category_id = 81 WHERE recruitment_id = 74;
-- Matched: '데이터분석' -> '데이터분석' (1.0000)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 75;
-- Matched: 'SW개발' -> '서버·백엔드개발' (0.5228)
UPDATE recruitment SET category_id = 93 WHERE recruitment_id = 76;
-- Matched: 'HW개발' -> 'HW·임베디드' (0.6185)
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 77;
-- Matched: '기술영업' -> 'IT·솔루션·기술영업' (0.6641)
UPDATE recruitment SET category_id = 5 WHERE recruitment_id = 78;
-- Matched: '전략소싱' -> '경영전략' (0.5958)
UPDATE recruitment SET category_id = 56 WHERE recruitment_id = 79;
-- Matched: '표시 컨설팅 서비스 담당(수출상품 표시분야)' -> '무역·수출입관리' (0.5412)
UPDATE recruitment SET category_id = 40 WHERE recruitment_id = 80;
-- Matched: '상품 기획' -> '상품기획' (0.9246)
UPDATE recruitment SET category_id = 39 WHERE recruitment_id = 81;
-- Matched: '마케팅' -> '마케팅전략·기획' (0.7821)
UPDATE recruitment SET category_id = 161 WHERE recruitment_id = 82;
-- Matched: '자동차 수요, 공급 관리' -> '자동차' (0.6397)
UPDATE recruitment SET category_id = 161 WHERE recruitment_id = 83;
-- Matched: '자동차 인증' -> '자동차' (0.6905)
UPDATE recruitment SET category_id = 19 WHERE recruitment_id = 84;
-- Matched: 'IT' -> 'IR' (0.5281)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 85;
-- Matched: '영업팀' -> '해외영업' (0.6767)
UPDATE recruitment SET category_id = 162 WHERE recruitment_id = 86;
-- Matched: '기계' -> '기계' (1.0000)
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 87;
-- Matched: '제조 Operator' -> '생산·제조·설비·조립' (0.4918)
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 88;
-- Matched: '제조 Operator (보훈제한경쟁)' -> '생산·제조·설비·조립' (0.4790)
UPDATE recruitment SET category_id = 101 WHERE recruitment_id = 89;
-- Matched: '공정기술 (Cleaning)' -> '공정관리' (0.5725)
UPDATE recruitment SET category_id = 95 WHERE recruitment_id = 90;
-- Matched: 'YE (수율개선)' -> 'SW·솔루션·ERP' (0.3977)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 91;
-- Matched: '글로벌 웹 서비스 기획 (Junior)' -> '서비스기획·PM' (0.5971)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 93;
-- Matched: '기술연구소 반도체 TEST 장비 제어 SW 개발' -> '반도체·디스플레이' (0.5274)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 94;
-- Matched: '기술연구소 반도체 TEST 장비 제어 SW 개발' -> '반도체·디스플레이' (0.5275)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 95;
-- Matched: '반도체 해외 영업/마케터' -> '해외영업' (0.6706)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 96;
-- Matched: '반도체 해외 영업/마케터' -> '해외영업' (0.6706)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 97;
-- Matched: '반도체 불량분석/연계분석 엔지니어' -> '반도체·디스플레이' (0.5848)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 98;
-- Matched: '반도체 불량분석/연계분석 엔지니어' -> '반도체·디스플레이' (0.5844)
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 99;
-- Matched: '[인턴] 세일즈 스페셜리스트' -> 'IT·솔루션·기술영업' (0.4720)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 100;
-- Matched: '차량용 반도체 임베디드 스쿨 4기' -> '반도체·디스플레이' (0.4832)
UPDATE recruitment SET category_id = 111 WHERE recruitment_id = 101;
-- Matched: 'Field Service Engineer' -> '설치·정비·AS·시공·공무' (0.4379)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 102;
-- Matched: '정책 기획 및 기술사업화 컨설팅' -> '사업기획' (0.6573)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 103;
-- Matched: '행정7급' -> '현장·시공·감리·공무' (0.5265)
UPDATE recruitment SET category_id = 235 WHERE recruitment_id = 104;
-- Matched: '기술7급' -> '외국어·자격증·기술강사' (0.4840)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 105;
-- Matched: '정규직_일반행정' -> '일반사무' (0.6265)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 106;
-- Matched: '정규직_정보(지능정보)' -> '현장·시공·감리·공무' (0.4980)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 107;
-- Matched: '정규직_사서' -> '일반사무' (0.5796)
UPDATE recruitment SET category_id = 141 WHERE recruitment_id = 108;
-- Matched: '정규직_건축' -> '건축·설계·인테리어' (0.6366)
UPDATE recruitment SET category_id = 33 WHERE recruitment_id = 109;
-- Matched: '정규직_법무/노무' -> '법무' (0.6551)
UPDATE recruitment SET category_id = 50 WHERE recruitment_id = 110;
-- Matched: '물류자산관리 (제주)' -> '물류관리·기획' (0.6677)
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 112;
-- Matched: 'Assembly / Bump Engineer' -> '생산·제조·설비·조립' (0.3593)
UPDATE recruitment SET category_id = 69 WHERE recruitment_id = 113;
-- Matched: 'Test Engineer' -> 'QA' (0.4620)
UPDATE recruitment SET category_id = 69 WHERE recruitment_id = 114;
-- Matched: 'Test Development Engineer' -> 'QA' (0.4188)
UPDATE recruitment SET category_id = 69 WHERE recruitment_id = 115;
-- Matched: 'Test IT Engineer' -> 'QA' (0.4403)
UPDATE recruitment SET category_id = 69 WHERE recruitment_id = 116;
-- Matched: 'Quality Engineer' -> 'QA' (0.5221)
UPDATE recruitment SET category_id = 72 WHERE recruitment_id = 117;
-- Matched: 'Application 개발' -> '안드로이드개발' (0.6745)
UPDATE recruitment SET category_id = 95 WHERE recruitment_id = 118;
-- Matched: '공장자동화 S/W 개발' -> 'SW·솔루션·ERP' (0.5204)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 119;
-- Matched: '생산/고객관리' -> '생산관리' (0.7918)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 120;
-- Matched: '생산기획 (Industrial Engineering)' -> '생산관리' (0.6852)
UPDATE recruitment SET category_id = 9 WHERE recruitment_id = 121;
-- Matched: '인사' -> '인사' (1.0000)
UPDATE recruitment SET category_id = 11 WHERE recruitment_id = 122;
-- Matched: '교육' -> '교육' (1.0000)
UPDATE recruitment SET category_id = 28 WHERE recruitment_id = 123;
-- Matched: '총무' -> '총무' (1.0000)
UPDATE recruitment SET category_id = 72 WHERE recruitment_id = 124;
-- Matched: '공장자동화 H/W 개발' -> '안드로이드개발' (0.4828)
UPDATE recruitment SET category_id = 72 WHERE recruitment_id = 125;
-- Matched: 'RF Module 개발' -> '안드로이드개발' (0.4641)
UPDATE recruitment SET category_id = 197 WHERE recruitment_id = 126;
-- Matched: '제품개발' -> '제품·산업디자인' (0.7306)
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 127;
-- Matched: 'Assembly / Bump Engineer' -> '생산·제조·설비·조립' (0.3593)
UPDATE recruitment SET category_id = 69 WHERE recruitment_id = 128;
-- Matched: 'Test Engineer' -> 'QA' (0.4620)
UPDATE recruitment SET category_id = 69 WHERE recruitment_id = 129;
-- Matched: 'Test Development Engineer' -> 'QA' (0.4188)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 130;
-- Matched: '생산/고객관리' -> '생산관리' (0.7918)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 131;
-- Matched: '생산기획 (Industrial Engineering)' -> '생산관리' (0.6852)
UPDATE recruitment SET category_id = 28 WHERE recruitment_id = 132;
-- Matched: '총무' -> '총무' (1.0000)
UPDATE recruitment SET category_id = 72 WHERE recruitment_id = 133;
-- Matched: '공장자동화 H/W 개발' -> '안드로이드개발' (0.4828)
UPDATE recruitment SET category_id = 227 WHERE recruitment_id = 134;
-- Matched: '소방 (위험물)' -> '보안·경비·경호' (0.5822)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 135;
-- Matched: '소방 (운영관리)' -> '안전관리' (0.5929)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 136;
-- Matched: '안전관리' -> '안전관리' (1.0000)
UPDATE recruitment SET category_id = 106 WHERE recruitment_id = 137;
-- Matched: '환경 운영' -> '환경관리' (0.8075)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 138;
-- Matched: '공사현장 안전관리' -> '안전관리' (0.7444)
UPDATE recruitment SET category_id = 221 WHERE recruitment_id = 139;
-- Matched: 'AI·SW마에스트로 연수생 (서울센터)' -> '외국어·번역·통역' (0.3943)
UPDATE recruitment SET category_id = 221 WHERE recruitment_id = 140;
-- Matched: 'AI·SW마에스트로 연수생 (부산센터)' -> '외국어·번역·통역' (0.3854)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 141;
-- Matched: '[일반전형]부산 본사' -> '일반사무' (0.5442)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 142;
-- Matched: '[일반전형]서울중부지사' -> '일반사무' (0.5628)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 143;
-- Matched: '[일반전형]서울남부지사' -> '일반사무' (0.5029)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 144;
-- Matched: '[일반전형]서울북부지사' -> '일반사무' (0.5318)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 145;
-- Matched: '[일반전형]서울동부지사' -> '일반사무' (0.5306)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 146;
-- Matched: '[일반전형]서울서부지사' -> '일반사무' (0.5127)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 147;
-- Matched: '[일반전형]수도권기업금융센터' -> '금융·보험영업' (0.5927)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 148;
-- Matched: '[일반전형]수도권서부종합금융센터' -> '금융·보험영업' (0.5225)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 149;
-- Matched: '[일반전형]인천지사' -> '일반사무' (0.4574)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 150;
-- Matched: '[일반전형]인천남부지사' -> '일반사무' (0.4750)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 151;
-- Matched: '[일반전형]경기중부지사' -> '일반사무' (0.5488)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 152;
-- Matched: '[일반전형]경기남부지사' -> '일반사무' (0.5130)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 153;
-- Matched: '[일반전형]경기북부지사' -> '일반사무' (0.5140)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 154;
-- Matched: '[일반전형]경기동부지사' -> '일반사무' (0.5681)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 155;
-- Matched: '[일반전형]강원동부지사' -> '일반사무' (0.5003)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 156;
-- Matched: '[일반전형]강원서부지사' -> '일반사무' (0.5036)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 157;
-- Matched: '[일반전형]부산지사' -> '일반사무' (0.5538)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 158;
-- Matched: '[일반전형]서부산지사' -> '일반사무' (0.4997)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 159;
-- Matched: '[일반전형]HF기업금융센터' -> '금융·보험영업' (0.5702)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 160;
-- Matched: '[일반전형]대구지사' -> '일반사무' (0.4853)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 161;
-- Matched: '[일반전형]울산지사' -> '일반사무' (0.4984)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 162;
-- Matched: '[일반전형]경북지사' -> '일반사무' (0.5099)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 163;
-- Matched: '[일반전형]경남지사' -> '일반사무' (0.4982)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 164;
-- Matched: '[일반전형]진주사무소' -> '일반사무' (0.5834)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 165;
-- Matched: '[일반전형]제주지사' -> '현장·시공·감리·공무' (0.4492)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 166;
-- Matched: '[일반전형]광주지사' -> '일반사무' (0.4968)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 167;
-- Matched: '[일반전형]대전지사' -> '일반사무' (0.5082)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 168;
-- Matched: '[일반전형]서남권종합금융센터' -> '금융·보험영업' (0.5359)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 169;
-- Matched: '[일반전형]세종지사' -> '현장·시공·감리·공무' (0.4058)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 170;
-- Matched: '[일반전형]충북지사' -> '일반사무' (0.4493)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 171;
-- Matched: '[일반전형]충남지사' -> '현장·시공·감리·공무' (0.4624)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 172;
-- Matched: '[일반전형]전북지사' -> '일반사무' (0.5409)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 173;
-- Matched: '[일반전형]전남지사' -> '현장·시공·감리·공무' (0.4854)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 174;
-- Matched: '[장애인특별전형]서울·경기 소재 지사' -> '현장·시공·감리·공무' (0.4108)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 175;
-- Matched: '[장애인특별전형]부산 소재 본·지사' -> '일반사무' (0.4017)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 176;
-- Matched: '프로모션 기획 및 실행' -> '사업기획' (0.5966)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 177;
-- Matched: '프로모션 기획 및 실행' -> '사업기획' (0.5966)
UPDATE recruitment SET category_id = 75 WHERE recruitment_id = 178;
-- Matched: '제로트러스트 보안 서비스 개발' -> '프론트엔드개발' (0.4808)
UPDATE recruitment SET category_id = 135 WHERE recruitment_id = 179;
-- Matched: '통신' -> '전기·통신' (0.6532)
UPDATE recruitment SET category_id = 199 WHERE recruitment_id = 180;
-- Matched: '건축' -> '건축·인테리어디자인' (0.7106)
UPDATE recruitment SET category_id = 203 WHERE recruitment_id = 181;
-- Matched: '승강PSD' -> 'UI·UX디자인' (0.4375)
UPDATE recruitment SET category_id = 161 WHERE recruitment_id = 182;
-- Matched: '차량 일반' -> '자동차' (0.5757)
UPDATE recruitment SET category_id = 161 WHERE recruitment_id = 183;
-- Matched: '차량 보훈' -> '자동차' (0.5307)
UPDATE recruitment SET category_id = 28 WHERE recruitment_id = 184;
-- Matched: '승무' -> '총무' (0.5595)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 185;
-- Matched: '해외영업' -> '해외영업' (1.0000)
UPDATE recruitment SET category_id = 106 WHERE recruitment_id = 186;
-- Matched: '환경안전' -> '환경관리' (0.7250)
UPDATE recruitment SET category_id = 91 WHERE recruitment_id = 187;
-- Matched: 'AI 데이터 엔지니어' -> '빅데이터·AI' (0.6181)
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 188;
-- Matched: '제조혁신(AX/DX)' -> '생산·제조·설비·조립' (0.4557)
UPDATE recruitment SET category_id = 69 WHERE recruitment_id = 189;
-- Matched: 'Quality Control Analyst' -> 'QA' (0.4945)
UPDATE recruitment SET category_id = 59 WHERE recruitment_id = 190;
-- Matched: '입찰' -> '구매' (0.6396)
UPDATE recruitment SET category_id = 167 WHERE recruitment_id = 191;
-- Matched: '환경' -> '환경' (1.0000)
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 192;
-- Matched: '사무지원' -> '사무보조' (0.8044)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 193;
-- Matched: '[교원구몬] 플랫폼 백엔드 개발' -> '서버·백엔드개발' (0.6079)
UPDATE recruitment SET category_id = 197 WHERE recruitment_id = 194;
-- Matched: '[교원Wells] 제품 기구 설계' -> '제품·산업디자인' (0.5546)
UPDATE recruitment SET category_id = 197 WHERE recruitment_id = 195;
-- Matched: '[교원Wells] 제품 기구 설계' -> '제품·산업디자인' (0.5546)
UPDATE recruitment SET category_id = 156 WHERE recruitment_id = 196;
-- Matched: '[교원Wells] 신뢰성 검증' -> '은행원' (0.4050)
UPDATE recruitment SET category_id = 197 WHERE recruitment_id = 197;
-- Matched: '[교원Wells] 제품 개발 (회로전장)' -> '제품·산업디자인' (0.4748)
UPDATE recruitment SET category_id = 38 WHERE recruitment_id = 198;
-- Matched: '[교원Wells] 온라인 총괄 판매' -> '퍼포먼스·온라인마케팅' (0.4708)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 199;
-- Matched: '[교원Wells] 사업 기획' -> '사업기획' (0.6179)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 200;
-- Matched: '[교원Wells] 영업관리 (수도권)' -> '영업관리·지원·기획' (0.6034)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 201;
-- Matched: '[교원Wells] 영업관리 (경상권)' -> '영업관리·지원·기획' (0.6056)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 202;
-- Matched: '[교원Wells] 영업관리 (강원권)' -> '영업관리·지원·기획' (0.5933)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 203;
-- Matched: '[호텔사업] Revenue Manager' -> '영업관리·지원·기획' (0.5242)
UPDATE recruitment SET category_id = 89 WHERE recruitment_id = 204;
-- Matched: '[교원 위즈] 학원 운영 관리' -> '네트워크·보안·운영' (0.4988)
UPDATE recruitment SET category_id = 89 WHERE recruitment_id = 205;
-- Matched: '[교원 위즈] 학원 운영 관리' -> '네트워크·보안·운영' (0.4989)
UPDATE recruitment SET category_id = 168 WHERE recruitment_id = 206;
-- Matched: '화장품/뷰티 디바이스 상품기획' -> '화장품' (0.7102)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 207;
-- Matched: '경영기획부 FP＆A specialist' -> '경영기획' (0.6502)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 208;
-- Matched: '일반직' -> '일반사무' (0.6154)
UPDATE recruitment SET category_id = 33 WHERE recruitment_id = 209;
-- Matched: '변호사' -> '법무' (0.4887)
UPDATE recruitment SET category_id = 24 WHERE recruitment_id = 210;
-- Matched: '회계사' -> '회계' (0.8544)
UPDATE recruitment SET category_id = 203 WHERE recruitment_id = 211;
-- Matched: '[디자인] 뷰티 VMD 디자이너 채용연계형 인턴사원 모집' -> 'UI·UX디자인' (0.4629)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 213;
-- Matched: '해외영업' -> '해외영업' (1.0000)
UPDATE recruitment SET category_id = 101 WHERE recruitment_id = 214;
-- Matched: '공정개발' -> '공정관리' (0.7261)
UPDATE recruitment SET category_id = 197 WHERE recruitment_id = 215;
-- Matched: '제품개발' -> '제품·산업디자인' (0.7306)
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 216;
-- Matched: '기술' -> 'IT·솔루션·기술영업' (0.4875)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 217;
-- Matched: '일반 (정규직) - 사원 (6급)' -> '일반사무' (0.5321)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 218;
-- Matched: '일반(선임)' -> '일반사무' (0.5759)
UPDATE recruitment SET category_id = 175 WHERE recruitment_id = 219;
-- Matched: '전산(선임)' -> '기계설계·CAD·CAM' (0.4119)
UPDATE recruitment SET category_id = 206 WHERE recruitment_id = 220;
-- Matched: '교양제작 PD' -> '연출·제작·PD·작가' (0.6782)
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 221;
-- Matched: '비히클실링 생산기술' -> '생산·제조·설비·조립' (0.4334)
UPDATE recruitment SET category_id = 137 WHERE recruitment_id = 222;
-- Matched: '비히클실링 압출기술' -> '기계·설비·화학' (0.3172)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 223;
-- Matched: '비히클실링 품질관리' -> '품질관리' (0.7105)
UPDATE recruitment SET category_id = 229 WHERE recruitment_id = 224;
-- Matched: '헬스케어' -> '보건·의료' (0.5931)
UPDATE recruitment SET category_id = 190 WHERE recruitment_id = 225;
-- Matched: '디자인' -> '광고 디자인' (0.6388)
UPDATE recruitment SET category_id = 72 WHERE recruitment_id = 226;
-- Matched: '개임개발' -> '안드로이드개발' (0.6021)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 227;
-- Matched: '[영업] 올리브영 채널 영업 AMD 채용연계형 인턴사원 모집' -> '영업관리·지원·기획' (0.4521)
UPDATE recruitment SET category_id = 37 WHERE recruitment_id = 228;
-- Matched: 'Content Marketing Assistant' -> '콘텐츠마케팅' (0.5121)
UPDATE recruitment SET category_id = 69 WHERE recruitment_id = 229;
-- Matched: 'User Interview Assistant' -> 'QA' (0.3918)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 230;
-- Matched: '국내물류 B2B 출고운영' -> 'B2B영업·법인영업' (0.6518)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 231;
-- Matched: '[KP그룹]KP한석화학 LAB BIZ팀 백앤드 개발자' -> '서비스기획·PM' (0.4718)
UPDATE recruitment SET category_id = 152 WHERE recruitment_id = 232;
-- Matched: 'Risk Assistant' -> '보험계리사·손해사정' (0.4197)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 233;
-- Matched: '전문영업 서비스디자이너 (전국)' -> 'B2B영업·법인영업' (0.5342)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 236;
-- Matched: 'SCM Specialist 정규직' -> '서비스기획·PM' (0.4870)
UPDATE recruitment SET category_id = 105 WHERE recruitment_id = 237;
-- Matched: '안전보건 관리' -> '안전관리' (0.8320)
UPDATE recruitment SET category_id = 24 WHERE recruitment_id = 238;
-- Matched: '회계' -> '회계' (1.0000)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 239;
-- Matched: '경영지원' -> '경영기획' (0.7162)
UPDATE recruitment SET category_id = 126 WHERE recruitment_id = 240;
-- Matched: '[CS] 해외 CS 운영/관리 담당 채용연계형' -> '고객응대·CS' (0.5456)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 241;
-- Matched: '[CS] 해외 CS 운영/관리 담당' -> '해외영업' (0.5837)
UPDATE recruitment SET category_id = 89 WHERE recruitment_id = 242;
-- Matched: 'IT서비스 시스템 운영 및 개발' -> '네트워크·보안·운영' (0.6220)
UPDATE recruitment SET category_id = 12 WHERE recruitment_id = 243;
-- Matched: '채용연계형 인턴사원' -> '채용' (0.6521)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 244;
-- Matched: 'PDRN/PN 품질관리(QC)' -> '품질관리' (0.6758)
UPDATE recruitment SET category_id = 46 WHERE recruitment_id = 245;
-- Matched: '[마케팅] 싱가포르 인플루언서 마케팅(PR) 채용연계형 인턴사원 모집' -> '사내홍보' (0.4717)
UPDATE recruitment SET category_id = 124 WHERE recruitment_id = 246;
-- Matched: '인바운드 세일즈 스페셜리스트' -> '인바운드' (0.6288)
UPDATE recruitment SET category_id = 66 WHERE recruitment_id = 247;
-- Matched: '프로덕트 세일즈 스페셜리스트' -> '상품기획·MD' (0.5628)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 248;
-- Matched: '경영기획팀 선박보험/경영지원 매니저' -> '경영기획' (0.6128)
UPDATE recruitment SET category_id = 101 WHERE recruitment_id = 249;
-- Matched: '선박관리팀 공무감독' -> '공정관리' (0.5402)
UPDATE recruitment SET category_id = 28 WHERE recruitment_id = 250;
-- Matched: '부총장실' -> '총무' (0.6802)
UPDATE recruitment SET category_id = 221 WHERE recruitment_id = 251;
-- Matched: '한국어문화학부' -> '외국어·번역·통역' (0.5475)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 252;
-- Matched: '관광레저항공경영학과' -> '경영기획' (0.5193)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 253;
-- Matched: 'AI서비스 프론트/백엔드 신입 개발자' -> '서버·백엔드개발' (0.5736)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 254;
-- Matched: 'AI서비스 프론트/백엔드 경력 개발자' -> '서버·백엔드개발' (0.5502)
UPDATE recruitment SET category_id = 82 WHERE recruitment_id = 255;
-- Matched: 'Barista' -> 'DBA' (0.3542)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 256;
-- Matched: '사업운영 지원 매니저' -> '영업관리·지원·기획' (0.6797)
UPDATE recruitment SET category_id = 89 WHERE recruitment_id = 257;
-- Matched: '인프라 운영 및 엔지니어링(SE)' -> '네트워크·보안·운영' (0.5770)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 258;
-- Matched: '테크니컬 라이터' -> '반도체·디스플레이' (0.3977)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 259;
-- Matched: '테크니컬 라이터' -> '반도체·디스플레이' (0.3977)
UPDATE recruitment SET category_id = 81 WHERE recruitment_id = 260;
-- Matched: 'Online VOC 분석/운영' -> '데이터분석' (0.4663)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 261;
-- Matched: 'IDC 운영자 (광주)' -> '영업관리·지원·기획' (0.4868)
UPDATE recruitment SET category_id = 126 WHERE recruitment_id = 262;
-- Matched: 'CS 파트' -> '고객응대·CS' (0.4549)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 263;
-- Matched: '영업 2팀' -> 'B2B영업·법인영업' (0.6796)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 264;
-- Matched: '생산기술파트' -> '생산관리' (0.6854)
UPDATE recruitment SET category_id = 95 WHERE recruitment_id = 265;
-- Matched: 'SW파트' -> 'SW·솔루션·ERP' (0.4688)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 266;
-- Matched: '개발부(SW파트)' -> '서버·백엔드개발' (0.5227)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 267;
-- Matched: 'QC파트' -> '품질관리' (0.4195)
UPDATE recruitment SET category_id = 50 WHERE recruitment_id = 268;
-- Matched: '구매물류팀 구매/자재파트' -> '물류관리·기획' (0.5945)
UPDATE recruitment SET category_id = 69 WHERE recruitment_id = 269;
-- Matched: 'QA Assistant 인턴' -> 'QA' (0.5162)
UPDATE recruitment SET category_id = 101 WHERE recruitment_id = 270;
-- Matched: '사업관리/규제혁신' -> '공정관리' (0.6294)
UPDATE recruitment SET category_id = 91 WHERE recruitment_id = 271;
-- Matched: '사업관리/AI활용확산' -> '빅데이터·AI' (0.6166)
UPDATE recruitment SET category_id = 91 WHERE recruitment_id = 272;
-- Matched: '사업관리/AI헬스' -> '빅데이터·AI' (0.5546)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 273;
-- Matched: '사업관리/지역AX거점' -> '영업관리·지원·기획' (0.5845)
UPDATE recruitment SET category_id = 5 WHERE recruitment_id = 274;
-- Matched: '사업관리/글로벌전략' -> '경영전략' (0.7231)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 275;
-- Matched: '사업관리/글로벌창업' -> '영업관리·지원·기획' (0.6310)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 276;
-- Matched: '사업관리/글로벌협력' -> '영업관리·지원·기획' (0.6754)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 277;
-- Matched: '사업관리/ICT사업운영지원' -> '영업관리·지원·기획' (0.6418)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 278;
-- Matched: '경영관리/인사' -> '경영기획' (0.6499)
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 279;
-- Matched: '사무지원/ICT전략' -> '사무보조' (0.6158)
UPDATE recruitment SET category_id = 10 WHERE recruitment_id = 280;
-- Matched: '미화' -> '노무' (0.4447)
UPDATE recruitment SET category_id = 11 WHERE recruitment_id = 281;
-- Matched: '방카교육팀장' -> '교육' (0.4900)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 282;
-- Matched: '본사 수출영업부(중동)' -> '해외영업' (0.6314)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 283;
-- Matched: 'B2B마케팅' -> 'B2B영업·법인영업' (0.7919)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 284;
-- Matched: 'ERP서비스 백엔드 개발' -> '서버·백엔드개발' (0.6751)
UPDATE recruitment SET category_id = 66 WHERE recruitment_id = 285;
-- Matched: 'Design Assistant' -> '상품기획·MD' (0.4138)
UPDATE recruitment SET category_id = 69 WHERE recruitment_id = 286;
-- Matched: 'Research Assistant' -> 'QA' (0.4026)
UPDATE recruitment SET category_id = 69 WHERE recruitment_id = 287;
-- Matched: 'QA' -> 'QA' (1.0000)
UPDATE recruitment SET category_id = 80 WHERE recruitment_id = 288;
-- Matched: '[Cloud] Datadog Engineer' -> '데이터엔지니어' (0.4496)
UPDATE recruitment SET category_id = 80 WHERE recruitment_id = 289;
-- Matched: '[Cloud] Solutions Architect (Data Engineer)' -> '데이터엔지니어' (0.4329)
UPDATE recruitment SET category_id = 85 WHERE recruitment_id = 290;
-- Matched: '[Cloud] Solutions Architect (GCP)' -> '시스템프로그래머' (0.4080)
UPDATE recruitment SET category_id = 89 WHERE recruitment_id = 291;
-- Matched: '[Cloud] Cloud 보안' -> '네트워크·보안·운영' (0.5436)
UPDATE recruitment SET category_id = 89 WHERE recruitment_id = 292;
-- Matched: '[CDN] CDN 운영' -> '네트워크·보안·운영' (0.5280)
UPDATE recruitment SET category_id = 89 WHERE recruitment_id = 293;
-- Matched: '[보안] 침해분석 보안운영' -> '네트워크·보안·운영' (0.5898)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 294;
-- Matched: '[Contact Center PM] Project Manager' -> '서비스기획·PM' (0.5214)
UPDATE recruitment SET category_id = 126 WHERE recruitment_id = 295;
-- Matched: '[Contact Center] S/W개발 (Zendesk App)' -> '고객응대·CS' (0.4647)
UPDATE recruitment SET category_id = 126 WHERE recruitment_id = 296;
-- Matched: '[Contact Center] Zendesk Engineer' -> '고객응대·CS' (0.4300)
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 297;
-- Matched: '[Contact Center] Technical Architect' -> 'IT·솔루션·기술영업' (0.4229)
UPDATE recruitment SET category_id = 126 WHERE recruitment_id = 298;
-- Matched: '[Contact Center] 모바일 통화관리 시스템 개발' -> '고객응대·CS' (0.4637)
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 299;
-- Matched: '[Cloud&CDN] 기술영업' -> 'IT·솔루션·기술영업' (0.5746)
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 300;
-- Matched: '[Contact Center 영업] 기술영업' -> 'IT·솔루션·기술영업' (0.6142)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 301;
-- Matched: '[IT사업전략기획] 상품/사업전략기획' -> '사업기획' (0.6950)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 302;
-- Matched: '[IT수행부문] 기술기획' -> '서비스기획·PM' (0.6285)
UPDATE recruitment SET category_id = 80 WHERE recruitment_id = 303;
-- Matched: '[Cloud] Datadog Engineer' -> '데이터엔지니어' (0.4496)
UPDATE recruitment SET category_id = 85 WHERE recruitment_id = 304;
-- Matched: '[Cloud] Solutions Architect' -> '시스템프로그래머' (0.4148)
UPDATE recruitment SET category_id = 89 WHERE recruitment_id = 305;
-- Matched: '[CDN] CDN 운영' -> '네트워크·보안·운영' (0.5280)
UPDATE recruitment SET category_id = 126 WHERE recruitment_id = 306;
-- Matched: '[Contact Center] Zendesk Engineer' -> '고객응대·CS' (0.4300)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 307;
-- Matched: '[IT사업전략기획] 사업전략/HR기획' -> '사업기획' (0.6529)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 308;
-- Matched: '[IT수행부문] 기술기획' -> '서비스기획·PM' (0.6283)
UPDATE recruitment SET category_id = 145 WHERE recruitment_id = 309;
-- Matched: '[Cloud 빌링] Billing Data Operation' -> '부동산·영업·견적' (0.4356)
UPDATE recruitment SET category_id = 40 WHERE recruitment_id = 310;
-- Matched: '포장(경력)' -> '상품기획' (0.4342)
UPDATE recruitment SET category_id = 24 WHERE recruitment_id = 311;
-- Matched: '회계/자금' -> '회계' (0.8273)
UPDATE recruitment SET category_id = 66 WHERE recruitment_id = 312;
-- Matched: '기획MD' -> '상품기획·MD' (0.7668)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 313;
-- Matched: '영업/영업기획' -> '영업관리·지원·기획' (0.7923)
UPDATE recruitment SET category_id = 38 WHERE recruitment_id = 314;
-- Matched: '온라인 AMD' -> '퍼포먼스·온라인마케팅' (0.4541)
UPDATE recruitment SET category_id = 201 WHERE recruitment_id = 315;
-- Matched: '니트 디자이너' -> '의류·패션·잡화디자인' (0.4725)
UPDATE recruitment SET category_id = 201 WHERE recruitment_id = 316;
-- Matched: '우븐 디자이너' -> '의류·패션·잡화디자인' (0.4244)
UPDATE recruitment SET category_id = 199 WHERE recruitment_id = 317;
-- Matched: 'VMD (인테리어)' -> '건축·인테리어디자인' (0.5700)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 318;
-- Matched: '품질보증(신입)' -> '품질관리' (0.5816)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 319;
-- Matched: '품질경영 및 보증' -> '품질관리' (0.7881)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 320;
-- Matched: '이물검사(계약직)' -> '현장·시공·감리·공무' (0.4128)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 321;
-- Matched: '생산 IPC담당' -> '생산관리' (0.5942)
UPDATE recruitment SET category_id = 237 WHERE recruitment_id = 322;
-- Matched: '의료사회복지사(육아휴직 대체)' -> '사회복지·요양보호·자원봉사' (0.5852)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 324;
-- Matched: '행정기획' -> '경영기획' (0.7501)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 325;
-- Matched: '영업직(대리～과장급)' -> 'B2B영업·법인영업' (0.6167)
UPDATE recruitment SET category_id = 37 WHERE recruitment_id = 326;
-- Matched: 'AI 콘텐츠 최적화 (GEO)' -> '콘텐츠마케팅' (0.5376)
UPDATE recruitment SET category_id = 233 WHERE recruitment_id = 327;
-- Matched: '국가인적자원개발컨소시엄 운영' -> '교육개발·기획' (0.4920)
UPDATE recruitment SET category_id = 233 WHERE recruitment_id = 328;
-- Matched: '국가인적자원개발컨소시엄 운영' -> '교육개발·기획' (0.4920)
UPDATE recruitment SET category_id = 75 WHERE recruitment_id = 329;
-- Matched: 'Frontend Developer Assistant' -> '프론트엔드개발' (0.4168)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 330;
-- Matched: '일반행정 (국제협력)' -> '일반사무' (0.5864)
UPDATE recruitment SET category_id = 72 WHERE recruitment_id = 331;
-- Matched: 'AI 개발자 양성 과정' -> '안드로이드개발' (0.5306)
UPDATE recruitment SET category_id = 50 WHERE recruitment_id = 332;
-- Matched: '자재물류(신입)' -> '물류관리·기획' (0.5856)
UPDATE recruitment SET category_id = 199 WHERE recruitment_id = 333;
-- Matched: '일반직 4급 상당 기간제직원 (공간디자인)' -> '건축·인테리어디자인' (0.4773)
UPDATE recruitment SET category_id = 131 WHERE recruitment_id = 334;
-- Matched: '일반직 5급 상당 기간제직원 (전시)' -> '현장·시공·감리·공무' (0.4497)
UPDATE recruitment SET category_id = 101 WHERE recruitment_id = 335;
-- Matched: '기술운영직 (시설관리)' -> '공정관리' (0.5578)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 336;
-- Matched: '일반운영직 (방호)' -> '일반사무' (0.5338)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 337;
-- Matched: '일반운영직 (전시운영)' -> '일반사무' (0.5641)
UPDATE recruitment SET category_id = 50 WHERE recruitment_id = 338;
-- Matched: '물류 운영' -> '물류관리·기획' (0.8008)
UPDATE recruitment SET category_id = 30 WHERE recruitment_id = 339;
-- Matched: '연말정산 업무보조' -> '사무보조' (0.6056)
UPDATE recruitment SET category_id = 135 WHERE recruitment_id = 340;
-- Matched: 'KG 청년 이차전지 미래기술 아카데미 11기' -> '전기·통신' (0.3730)
UPDATE recruitment SET category_id = 87 WHERE recruitment_id = 341;
-- Matched: '소프트웨어 테스팅' -> '응용프로그래머' (0.4897)
UPDATE recruitment SET category_id = 203 WHERE recruitment_id = 342;
-- Matched: '피그마 UI 실무' -> 'UI·UX디자인' (0.5369)
UPDATE recruitment SET category_id = 203 WHERE recruitment_id = 343;
-- Matched: 'UX/UI 디자인' -> 'UI·UX디자인' (0.8983)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 344;
-- Matched: '핀테크 서비스 기획' -> '서비스기획·PM' (0.6131)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 345;
-- Matched: '초보 PM 현업 가이드' -> '서비스기획·PM' (0.5020)
UPDATE recruitment SET category_id = 81 WHERE recruitment_id = 346;
-- Matched: '캐글 데이터 분석' -> '데이터분석' (0.6102)
UPDATE recruitment SET category_id = 75 WHERE recruitment_id = 347;
-- Matched: '프론트엔드 실무' -> '프론트엔드개발' (0.7891)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 348;
-- Matched: '웹 개발 완벽가이드' -> '서버·백엔드개발' (0.5193)
UPDATE recruitment SET category_id = 91 WHERE recruitment_id = 349;
-- Matched: 'AI 챗봇 구축' -> '빅데이터·AI' (0.5083)
UPDATE recruitment SET category_id = 91 WHERE recruitment_id = 350;
-- Matched: 'MLOps와 온디바이스 AI' -> '빅데이터·AI' (0.6033)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 351;
-- Matched: '실전 DevOps 입문' -> '서버·백엔드개발' (0.4660)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 352;
-- Matched: '실전완성 AWS 클라우드' -> '서버·백엔드개발' (0.4448)
UPDATE recruitment SET category_id = 80 WHERE recruitment_id = 353;
-- Matched: 'MUSINSA ROOKIE AI NATIVE ENGINEER' -> '데이터엔지니어' (0.4403)
UPDATE recruitment SET category_id = 116 WHERE recruitment_id = 354;
-- Matched: '세일즈팀 ISR(Inside ​Sales ​Representative) ​(전환형 인턴)' -> 'IT·솔루션·기술영업' (0.4934)
UPDATE recruitment SET category_id = 118 WHERE recruitment_id = 355;
-- Matched: '풀리팀 B2G Sales Manager (전환형 인턴)' -> 'B2B영업·법인영업' (0.5780)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 356;
-- Matched: 'IDC 운영자 (광주)' -> '영업관리·지원·기획' (0.4868)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 357;
-- Matched: 'IDC 운영자(인재풀)' -> '서비스기획·PM' (0.4799)
UPDATE recruitment SET category_id = 80 WHERE recruitment_id = 359;
-- Matched: 'XE_전산팀' -> '데이터엔지니어' (0.4995)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 360;
-- Matched: 'XE_영업팀' -> '해외영업' (0.5565)
UPDATE recruitment SET category_id = 40 WHERE recruitment_id = 361;
-- Matched: 'XE_구매기획팀' -> '상품기획' (0.5830)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 362;
-- Matched: 'XE_품질관리팀' -> '품질관리' (0.6647)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 363;
-- Matched: 'XE_개발품질팀' -> '품질관리' (0.5571)
UPDATE recruitment SET category_id = 126 WHERE recruitment_id = 364;
-- Matched: '이씨스_구매조달팀' -> '고객응대·CS' (0.5163)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 365;
-- Matched: 'HF_영업팀' -> '해외영업' (0.5875)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 366;
-- Matched: 'XE_경영관리팀(팀장)' -> '경영기획' (0.5203)
UPDATE recruitment SET category_id = 106 WHERE recruitment_id = 367;
-- Matched: 'XE_경영관리팀' -> '환경관리' (0.5285)
UPDATE recruitment SET category_id = 219 WHERE recruitment_id = 368;
-- Matched: 'XE_연구관리팀' -> '리서치·시장조사' (0.4396)
UPDATE recruitment SET category_id = 5 WHERE recruitment_id = 369;
-- Matched: 'XE_사업전략팀' -> '경영전략' (0.5402)
UPDATE recruitment SET category_id = 197 WHERE recruitment_id = 370;
-- Matched: 'XE_제품기획팀(상품기획)' -> '제품·산업디자인' (0.5831)
UPDATE recruitment SET category_id = 95 WHERE recruitment_id = 371;
-- Matched: 'XE_제품기획팀(SW개발관리)' -> 'SW·솔루션·ERP' (0.5159)
UPDATE recruitment SET category_id = 40 WHERE recruitment_id = 372;
-- Matched: 'XE_구매기획팀' -> '상품기획' (0.5829)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 373;
-- Matched: 'XE_생산관리팀' -> '생산관리' (0.6094)
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 374;
-- Matched: 'XE_생산팀' -> '생산·제조·설비·조립' (0.5412)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 375;
-- Matched: 'XE_원가혁신팀(프로세스혁신)' -> '서비스기획·PM' (0.4430)
UPDATE recruitment SET category_id = 156 WHERE recruitment_id = 376;
-- Matched: 'XE_원가혁신팀(가격혁신)' -> '은행원' (0.4100)
UPDATE recruitment SET category_id = 95 WHERE recruitment_id = 377;
-- Matched: 'XE_SW설계팀' -> 'SW·솔루션·ERP' (0.4890)
UPDATE recruitment SET category_id = 75 WHERE recruitment_id = 378;
-- Matched: 'XE_SW개발팀' -> '프론트엔드개발' (0.5005)
UPDATE recruitment SET category_id = 93 WHERE recruitment_id = 379;
-- Matched: 'XE_HW설계팀' -> 'HW·임베디드' (0.5220)
UPDATE recruitment SET category_id = 197 WHERE recruitment_id = 380;
-- Matched: 'XE_기구설계팀' -> '제품·산업디자인' (0.5322)
UPDATE recruitment SET category_id = 97 WHERE recruitment_id = 381;
-- Matched: 'XE_시험평가팀' -> '서비스기획·PM' (0.4237)
UPDATE recruitment SET category_id = 102 WHERE recruitment_id = 382;
-- Matched: '이씨스_품질관리팀' -> '품질관리' (0.6933)
UPDATE recruitment SET category_id = 225 WHERE recruitment_id = 383;
-- Matched: '이씨스_재무회계팀' -> '회계·세무·CPA·CFA' (0.5720)
UPDATE recruitment SET category_id = 59 WHERE recruitment_id = 384;
-- Matched: '이씨스_구매조달팀(자재)' -> '구매' (0.5011)
UPDATE recruitment SET category_id = 59 WHERE recruitment_id = 385;
-- Matched: '이씨스_구매조달팀(구매)' -> '구매' (0.5254)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 386;
-- Matched: '산업_경영지원팀(인사총무)' -> '영업관리·지원·기획' (0.6357)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 387;
-- Matched: '산업_기획관리팀' -> '경영기획' (0.6852)
UPDATE recruitment SET category_id = 109 WHERE recruitment_id = 388;
-- Matched: '산업_생산기술팀' -> '생산·제조·설비·조립' (0.6878)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 389;
-- Matched: '산업_해외영업팀' -> '해외영업' (0.7478)
UPDATE recruitment SET category_id = 233 WHERE recruitment_id = 390;
-- Matched: '인력개발' -> '교육개발·기획' (0.6059)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 391;
-- Matched: '영업' -> '해외영업' (0.7247)
UPDATE recruitment SET category_id = 126 WHERE recruitment_id = 392;
-- Matched: '고객서비스' -> '고객응대·CS' (0.7948)
UPDATE recruitment SET category_id = 150 WHERE recruitment_id = 393;
-- Matched: '자산운용' -> '외환·펀드·자산운용' (0.6182)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 394;
-- Matched: '시스템개발(Java)' -> '서버·백엔드개발' (0.5738)
UPDATE recruitment SET category_id = 85 WHERE recruitment_id = 395;
-- Matched: '시스템개발(SAP)' -> '시스템프로그래머' (0.5956)
UPDATE recruitment SET category_id = 85 WHERE recruitment_id = 396;
-- Matched: '시스템개발(금융)' -> '시스템프로그래머' (0.5651)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 397;
-- Matched: '모바일개발(Back-end)' -> '서버·백엔드개발' (0.7113)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 398;
-- Matched: '클라우드엔지니어(On-Premise/Cloud)' -> '서버·백엔드개발' (0.4910)
UPDATE recruitment SET category_id = 150 WHERE recruitment_id = 399;
-- Matched: '자산 관리' -> '외환·펀드·자산운용' (0.5844)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 400;
-- Matched: '국가연구개발사업 기획 및 사업관리' -> '사업기획' (0.6381)
UPDATE recruitment SET category_id = 46 WHERE recruitment_id = 401;
-- Matched: '2026 공공기관 채용정보박람회' -> '사내홍보' (0.4334)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 402;
-- Matched: '일반직군' -> '일반사무' (0.5037)
UPDATE recruitment SET category_id = 28 WHERE recruitment_id = 403;
-- Matched: '전산직군' -> '총무' (0.4085)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 404;
-- Matched: '경영 기획 - 인사·교육 (4급 대리)' -> '경영기획' (0.6333)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 405;
-- Matched: '사업 기획·운영 - 국제문화교류 사업 기획·운영A (4급 대리)' -> '영업관리·지원·기획' (0.5398)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 406;
-- Matched: '사업 기획·운영 - 국제문화교류 사업 기획·운영B (4급 대리)' -> '영업관리·지원·기획' (0.5510)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 407;
-- Matched: '경영 기획 - 전략기획 (5급 사원)' -> '경영기획' (0.6805)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 408;
-- Matched: '경영 기획 - 대외협력 (5급 사원)' -> '경영기획' (0.5642)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 409;
-- Matched: '사업 기획·운영 -  국제문화교류 사업 기획·운영 (5급 사원)' -> '사업기획' (0.4872)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 410;
-- Matched: '사업 기획·운영 -  국제문화교류 사업 기획·운영 (4급 대리, 휴직대체)' -> '영업관리·지원·기획' (0.5290)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 411;
-- Matched: '경영 기획 - 경영 지원 (5급 사원, 휴직대체)' -> '경영기획' (0.6416)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 412;
-- Matched: '사업 기획·운영 - 국제문화교류 사업 기획·운영A(5급 사원, 계약직)' -> '사업기획' (0.4925)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 413;
-- Matched: '사업 기획·운영 - 국제문화교류 사업 기획·운영B (5급 사원, 계약직)' -> '사업기획' (0.4978)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 414;
-- Matched: '영업점 업무 지원' -> '영업관리·지원·기획' (0.7589)
UPDATE recruitment SET category_id = 55 WHERE recruitment_id = 415;
-- Matched: '본점' -> '해외영업' (0.4290)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 416;
-- Matched: '서울동부지역본부' -> '영업관리·지원·기획' (0.4826)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 417;
-- Matched: '인천지역본부' -> '영업관리·지원·기획' (0.4519)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 418;
-- Matched: '경기지역본부' -> '영업관리·지원·기획' (0.4923)
UPDATE recruitment SET category_id = 28 WHERE recruitment_id = 419;
-- Matched: '충청지역본부' -> '총무' (0.4120)
UPDATE recruitment SET category_id = 46 WHERE recruitment_id = 420;
-- Matched: '호남지역본부' -> '사내홍보' (0.4698)
UPDATE recruitment SET category_id = 9 WHERE recruitment_id = 421;
-- Matched: '본점(인사부)' -> '인사' (0.4919)
UPDATE recruitment SET category_id = 76 WHERE recruitment_id = 422;
-- Matched: '웹 프론트엔드 개발' -> '서버·백엔드개발' (0.7046)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 423;
-- Matched: '[ENF]경영기획' -> '경영기획' (0.7417)
UPDATE recruitment SET category_id = 120 WHERE recruitment_id = 424;
-- Matched: '[ENF]사업지원' -> '영업관리·지원·기획' (0.5709)
UPDATE recruitment SET category_id = 44 WHERE recruitment_id = 425;
-- Matched: '[ENF]연구개발(Color Paste/CNT)' -> '광고제작·카피' (0.3851)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 426;
-- Matched: '[ENF]연구개발(반도체재료)' -> '반도체·디스플레이' (0.5909)
UPDATE recruitment SET category_id = 179 WHERE recruitment_id = 427;
-- Matched: '[ENF]개발지원(반도체재료)' -> '반도체·디스플레이' (0.5811)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 428;
-- Matched: '[ENF]생산보조' -> '생산관리' (0.5725)
UPDATE recruitment SET category_id = 56 WHERE recruitment_id = 429;
-- Matched: '[ENF]출하보조' -> '무역·수출입관리' (0.4589)
UPDATE recruitment SET category_id = 100 WHERE recruitment_id = 430;
-- Matched: '[ENF]생산운전' -> '생산관리' (0.5263)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 431;
-- Matched: '[KC&A]신규사업' -> '사업기획' (0.5324)
UPDATE recruitment SET category_id = 50 WHERE recruitment_id = 432;
-- Matched: '[KAI]구매물류' -> '물류관리·기획' (0.5620)
UPDATE recruitment SET category_id = 101 WHERE recruitment_id = 433;
-- Matched: '[KAI]공정기술' -> '공정관리' (0.4792)
UPDATE recruitment SET category_id = 106 WHERE recruitment_id = 434;
-- Matched: '[KAI]환경관리' -> '환경관리' (0.7636)
UPDATE recruitment SET category_id = 28 WHERE recruitment_id = 435;
-- Matched: '[KAI]총무' -> '총무' (0.6781)
UPDATE recruitment SET category_id = 28 WHERE recruitment_id = 436;
-- Matched: '[PURIT]총무' -> '총무' (0.6816)
UPDATE recruitment SET category_id = 101 WHERE recruitment_id = 437;
-- Matched: '[PURIT]기계관리' -> '공정관리' (0.5786)
UPDATE recruitment SET category_id = 72 WHERE recruitment_id = 438;
-- Matched: '[NFC]연구개발' -> '안드로이드개발' (0.4491)
UPDATE recruitment SET category_id = 126 WHERE recruitment_id = 439;
-- Matched: '클라우드 기술지원' -> '고객응대·CS' (0.4960)
UPDATE recruitment SET category_id = 27 WHERE recruitment_id = 440;
-- Matched: '행정부 사무직' -> '일반사무' (0.6324)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 441;
-- Matched: '산업금융' -> '금융·보험영업' (0.6238)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 442;
-- Matched: '리테일금융1' -> '금융·보험영업' (0.5123)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 443;
-- Matched: '리테일금융2' -> '금융·보험영업' (0.5204)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 444;
-- Matched: '오토금융' -> '금융·보험영업' (0.5814)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 445;
-- Matched: '기업금융' -> '금융·보험영업' (0.7082)
UPDATE recruitment SET category_id = 3 WHERE recruitment_id = 446;
-- Matched: '경영지원' -> '경영기획' (0.7162)
UPDATE recruitment SET category_id = 5 WHERE recruitment_id = 447;
-- Matched: '전략' -> '경영전략' (0.7135)
UPDATE recruitment SET category_id = 154 WHERE recruitment_id = 448;
-- Matched: '여신심사' -> '채권·심사' (0.4473)
UPDATE recruitment SET category_id = 237 WHERE recruitment_id = 449;
-- Matched: '여신지원' -> '사회복지·요양보호·자원봉사' (0.4446)
UPDATE recruitment SET category_id = 4 WHERE recruitment_id = 450;
-- Matched: '기획 및 개발' -> '사업기획' (0.6899)
UPDATE recruitment SET category_id = 128 WHERE recruitment_id = 451;
-- Matched: '기업금융' -> '금융·보험영업' (0.7082)
UPDATE recruitment SET category_id = 24 WHERE recruitment_id = 452;
-- Matched: '회계' -> '회계' (1.0000)
UPDATE recruitment SET category_id = 28 WHERE recruitment_id = 453;
-- Matched: '총무' -> '총무' (1.0000)
UPDATE recruitment SET category_id = 13 WHERE recruitment_id = 454;
-- Matched: '급여' -> '급여' (1.0000)
UPDATE recruitment SET category_id = 82 WHERE recruitment_id = 455;
-- Matched: 'IT Admin' -> 'DBA' (0.4827)

-- Total Updated: 448
