spring:
  application:
    name: ozazak-presentation
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:ozazak}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
