spring:
  application:
    name: ozazak-presentation
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:ozazak}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:test@gmail.com}
    password: ${MAIL_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET}