#!/usr/bin/env python3
"""
job_title.txt를 읽어 recruitment 테이블에 position 컬럼 추가 및 데이터 입력하는 Flyway SQL 생성
"""

import time

INPUT_FILE = "job_title.txt"
OUTPUT_SQL = "V20260202130000__add_recruitment_position.sql"

def escape_sql(text):
    """SQL 인젝션 방지를 위해 싱글 쿼트 이스케이프"""
    if text is None:
        return ""
    return text.replace("'", "''")

def main():
    # 1. job_title.txt 읽기
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        lines = f.readlines()
    
    # 헤더 제거 (첫 줄이 "직무명")
    if lines and lines[0].strip() == "직무명":
        lines = lines[1:]
    
    # 빈 줄 제거하지 않고 순서 유지 (recruitment_id와 1:1 매칭)
    job_titles = [line.strip() for line in lines]
    
    print(f"📊 총 {len(job_titles)}개 직무 데이터 로드됨")
    
    # 2. SQL 파일 생성
    with open(OUTPUT_SQL, "w", encoding="utf-8") as sql_file:
        sql_file.write("-- Generated by generate_position_flyway.py\n")
        sql_file.write(f"-- Date: {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        
        # Phase 1: position 컬럼 추가
        sql_file.write("-- ========================================\n")
        sql_file.write("-- 1. Add position column to recruitment\n")
        sql_file.write("-- ========================================\n\n")
        sql_file.write("ALTER TABLE recruitment ADD COLUMN IF NOT EXISTS position VARCHAR(500);\n\n")
        
        # Phase 2: position 데이터 업데이트
        sql_file.write("-- ========================================\n")
        sql_file.write("-- 2. Update position data\n")
        sql_file.write("-- ========================================\n\n")
        
        count = 0
        for idx, title in enumerate(job_titles, start=1):
            if title:  # 빈 문자열이 아닌 경우만
                escaped_title = escape_sql(title)
                sql_file.write(f"UPDATE recruitment SET position = '{escaped_title}' WHERE recruitment_id = {idx};\n")
                count += 1
        
        sql_file.write(f"\n-- Total: {count} recruitments updated\n")
    
    print(f"✅ '{OUTPUT_SQL}' 파일 생성 완료! ({count}개 UPDATE문)")

if __name__ == "__main__":
    main()
