
import os
import time
import math
import psycopg2
from openai import OpenAI
from dotenv import load_dotenv

# 1. Load Environment Variables
load_dotenv()

GMS_KEY = os.getenv("GMS_API_KEY")
GMS_BASE_URL = "https://gms.ssafy.io/gmsapi/api.openai.com/v1"
EMBEDDING_MODEL = "text-embedding-3-large"
EMBEDDING_DIM = 1536
OUTPUT_SQL_FILE = "V20260202150000__update_recruitment_category_match.sql"

DB_CONFIG = {
    "host": "localhost",
    "database": "ozazak",
    "user": "b205admin",
    "password": "b205admin", 
    "port": "5432"
}

# 2. OpenAI Client
if not GMS_KEY:
    raise ValueError("❌ .env file missing 'GMS_API_KEY'")

client = OpenAI(api_key=GMS_KEY, base_url=GMS_BASE_URL)

def get_embedding(text, model=EMBEDDING_MODEL, dim=EMBEDDING_DIM):
    try:
        if not text or not text.strip():
            return None
        text = text.replace("\n", " ")
        resp = client.embeddings.create(
            model=model,
            input=[text],
            dimensions=dim
        )
        return resp.data[0].embedding
    except Exception as e:
        print(f"❌ OpenAI API Error: {e}")
        return None

def cosine_similarity(v1, v2):
    "Compute cosine similarity between two vectors."
    if not v1 or not v2: return 0.0
    
    dot_product = sum(a*b for a, b in zip(v1, v2))
    norm_a = math.sqrt(sum(a*a for a in v1))
    norm_b = math.sqrt(sum(b*b for b in v2))
    
    if norm_a == 0 or norm_b == 0: return 0.0
    return dot_product / (norm_a * norm_b)

def parse_vector_str(vec_str):
    "Parse string '[0.1, 0.2, ...]' into list of floats"
    if not vec_str: return None
    # Remove brackets and split
    clean = vec_str.strip("[]")
    if not clean: return None
    return [float(x) for x in clean.split(",")]

def main():
    conn = psycopg2.connect(**DB_CONFIG)
    cur = conn.cursor()
    
    print("🔌 DB Connected. Starting Recruitment-Category Mapping...")

    try:
        # 1. Fetch Categories
        # Fetch id, name, parent_id, embedding
        # Need to determine Depth 3.
        # Let's fetch all and build hierarchy in memory.
        print("📥 Fetching Categories...")
        cur.execute("SELECT id, name, parent_id, embedding FROM category")
        categories = cur.fetchall() # List of (id, name, parent_id, embedding_str or list)
        
        # Build map for parent lookup
        cat_map = {row[0]: {'name': row[1], 'parent_id': row[2], 'embedding': row[3]} for row in categories}
        
        target_categories = []
        
        for cat_id, data in cat_map.items():
            # Determine Depth
            depth = 1
            curr = data
            while curr['parent_id'] is not None:
                depth += 1
                parent_id = curr['parent_id']
                if parent_id in cat_map:
                    curr = cat_map[parent_id]
                else:
                    break # Orphan or root
            
            # User said: "category중에서도 depth가 3이었나 소분류가? 암튼 소분류에 해당하는 값들"
            # Assuming Depth 3 is the target leaf node.
            # Also ensure embedding exists
            if depth == 3 and data['embedding'] is not None:
                # Parse embedding if it's a string (pgvector returns string usually)
                vec = data['embedding']
                if isinstance(vec, str):
                    vec = parse_vector_str(vec)
                
                if vec:
                    target_categories.append({
                        'id': cat_id,
                        'name': data['name'],
                        'embedding': vec
                    })
        
        print(f"✅ Found {len(target_categories)} target categories (Depth 3 with embeddings).")
        
        if not target_categories:
            print("⚠️ No target categories found! Exiting.")
            return

        # 2. Load Recruitments from job_title.txt (Source of Truth)
        # We process line by line, assuming ID = 1..N
        INPUT_JOB_FILE = "job_title.txt"
        print(f"📖 Reading {INPUT_JOB_FILE}...")
        
        with open(INPUT_JOB_FILE, "r", encoding="utf-8") as f:
            lines = f.readlines()
            
        # Skip header
        if lines and lines[0].strip() == "직무명":
            lines = lines[1:]
            
        recruitments = []
        for idx, line in enumerate(lines, start=1):
            title = line.strip()
            if title:
                recruitments.append((idx, title))
        
        print(f"📊 Processing {len(recruitments)} recruitments from file...")
        
        updates = []
        
        with open(OUTPUT_SQL_FILE, "w", encoding="utf-8") as f:
            f.write("-- Generated by match_recruitment_category.py\n")
            f.write(f"-- Date: {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            
            count = 0
            for rec_id, position in recruitments:
                print(f"🔍 Processing [{count+1}/{len(recruitments)}] ID:{rec_id} Position: {position}")
                
                # Get embedding for position
                # Cache checking could be good, but for 450 items, API is fast enough.
                rec_vec = get_embedding(position)
                
                if not rec_vec:
                    print(f"   ⚠️ Skipping (No embedding generated)")
                    continue
                    
                # Find best match
                best_match = None
                max_score = -1.0
                
                for cat in target_categories:
                    score = cosine_similarity(rec_vec, cat['embedding'])
                    if score > max_score:
                        max_score = score
                        best_match = cat
                
                if best_match:
                    print(f"   ✅ Match: {best_match['name']} (Score: {max_score:.4f})")
                    
                    # Write SQL update
                    f.write(f"UPDATE recruitment SET category_id = {best_match['id']} WHERE recruitment_id = {rec_id};\n")
                    f.write(f"-- Matched: '{position}' -> '{best_match['name']}' ({max_score:.4f})\n")
                    count += 1
                else:
                    print("   ❓ No match found")
                    
                time.sleep(0.05) # Rate limit slightly
            
            f.write(f"\n-- Total Updated: {count}\n")
            
        print(f"🏁 Done! Generated {OUTPUT_SQL_FILE} with {count} updates.")

    except Exception as e:
        print(f"❌ Error: {e}")
    finally:
        cur.close()
        conn.close()

if __name__ == "__main__":
    main()
